# Textos da troca de linguagem da trilha (2026-10-04), nos três idiomas da web.
# No Starter a pessoa estuda uma família de linguagem por vez (GET /code/tracks: access "switch" e
# "not_in_plan" com changeAllowedAt; a troca é PUT /code/language-choice). Os nomes das trilhas e das
# etapas vêm da API já no idioma; aqui ficam os do exemplo.

TEXTOS = {
    'pt-BR': dict(
        tlRotulo='Troca de linguagem',
        tlJsTrilha='JavaScript do zero', tlPyTrilha='Python do zero',
        tlGuardado='Guardado', tlJsFeitas='5 de 12 etapas', tlPyFeitas='2 de 12 etapas',
        tlJsMeta='5 de 12 etapas · Funções e escopo', tlPyMeta='2 de 12 etapas · Variáveis e tipos',
        tlPyMetaNova='12 etapas · começa em Fundamentos',
        tlComeceAqui='comece aqui', tlDeOndeParou='de onde parou',
        tlIdaTit='Trocar para Python?',
        tlIdaTxt='No Starter você estuda uma linguagem por vez. JavaScript fica guardado em 5 de 12 etapas e volta inteiro, de onde parou, quando você voltar.',
        tlTrocarPy='Trocar para Python', tlFicarJs='Continuar em JavaScript',
        tlProLink='No Pro as duas ficam abertas',
        tlIdaTrocandoTit='Guardando JavaScript…',
        tlIdaTrocandoTxt='JavaScript congela do jeito que está, e Python abre em seguida.',
        tlIdaFimTit='Python aberto',
        tlIdaFimTxt='JavaScript ficou guardado em 5 de 12 etapas. Quando você voltar, ele descongela de onde parou.',
        tlComecar='Começar a trilha',
        tlVoltaTit='Voltar para JavaScript?',
        tlVoltaTxt='JavaScript descongela de onde parou, em 5 de 12 etapas. Python fica guardado em 2 de 12, do jeito que está.',
        tlVoltarJs='Voltar para JavaScript', tlFicarPy='Continuar em Python',
        tlVoltaTrocandoTit='Guardando Python…',
        tlVoltaTrocandoTxt='Python congela do jeito que está, e JavaScript descongela de onde parou.',
        tlVoltaFimTit='JavaScript de volta',
        tlVoltaFimTxt='Você continua de onde parou. Python ficou guardado em 2 de 12 etapas.',
        tlContinuar='Continuar a trilha',
        tlPlanoTit='Python libera em 12 de novembro',
        tlPlanoTxt='No Starter você estuda uma linguagem por vez, e a próxima troca fica liberada nessa data. Até lá, JavaScript segue aberto de onde parou.',
        tlPlanoPro='No Pro as duas ficam abertas.',
        tlVerPro='Ver o Pro', tlLiberaEm='libera em 12 de nov.',
    ),
    'en-US': dict(
        tlRotulo='Language switch',
        tlJsTrilha='JavaScript from scratch', tlPyTrilha='Python from scratch',
        tlGuardado='Saved', tlJsFeitas='5 of 12 steps', tlPyFeitas='2 of 12 steps',
        tlJsMeta='5 of 12 steps · Functions and scope', tlPyMeta='2 of 12 steps · Variables and types',
        tlPyMetaNova='12 steps · starts at Fundamentals',
        tlComeceAqui='start here', tlDeOndeParou='where you left off',
        tlIdaTit='Switch to Python?',
        tlIdaTxt='On Starter you study one language at a time. JavaScript is saved at 5 of 12 steps and comes back whole, right where you left off, when you return.',
        tlTrocarPy='Switch to Python', tlFicarJs='Stay on JavaScript',
        tlProLink='On Pro both stay open',
        tlIdaTrocandoTit='Saving JavaScript…',
        tlIdaTrocandoTxt='JavaScript freezes just as it is, and Python opens next.',
        tlIdaFimTit='Python is open',
        tlIdaFimTxt='JavaScript was saved at 5 of 12 steps. When you come back, it thaws right where you left off.',
        tlComecar='Start the track',
        tlVoltaTit='Go back to JavaScript?',
        tlVoltaTxt='JavaScript thaws where you left off, at 5 of 12 steps. Python is saved at 2 of 12, just as it is.',
        tlVoltarJs='Go back to JavaScript', tlFicarPy='Stay on Python',
        tlVoltaTrocandoTit='Saving Python…',
        tlVoltaTrocandoTxt='Python freezes just as it is, and JavaScript thaws where you left off.',
        tlVoltaFimTit='JavaScript is back',
        tlVoltaFimTxt='You pick up where you left off. Python was saved at 2 of 12 steps.',
        tlContinuar='Continue the track',
        tlPlanoTit='Python opens on November 12',
        tlPlanoTxt='On Starter you study one language at a time, and your next switch opens on that date. Until then, JavaScript stays open where you left off.',
        tlPlanoPro='On Pro both stay open.',
        tlVerPro='See Pro', tlLiberaEm='opens Nov 12',
    ),
    'es-ES': dict(
        tlRotulo='Cambio de lenguaje',
        tlJsTrilha='JavaScript desde cero', tlPyTrilha='Python desde cero',
        tlGuardado='Guardado', tlJsFeitas='5 de 12 etapas', tlPyFeitas='2 de 12 etapas',
        tlJsMeta='5 de 12 etapas · Funciones y alcance', tlPyMeta='2 de 12 etapas · Variables y tipos',
        tlPyMetaNova='12 etapas · empieza en Fundamentos',
        tlComeceAqui='empieza aquí', tlDeOndeParou='donde lo dejaste',
        tlIdaTit='¿Cambiar a Python?',
        tlIdaTxt='En Starter estudias un lenguaje a la vez. JavaScript queda guardado en 5 de 12 etapas y vuelve entero, donde lo dejaste, cuando regreses.',
        tlTrocarPy='Cambiar a Python', tlFicarJs='Seguir en JavaScript',
        tlProLink='En Pro los dos quedan abiertos',
        tlIdaTrocandoTit='Guardando JavaScript…',
        tlIdaTrocandoTxt='JavaScript se congela tal como está, y Python se abre enseguida.',
        tlIdaFimTit='Python abierto',
        tlIdaFimTxt='JavaScript quedó guardado en 5 de 12 etapas. Cuando regreses, se descongela donde lo dejaste.',
        tlComecar='Empezar la ruta',
        tlVoltaTit='¿Volver a JavaScript?',
        tlVoltaTxt='JavaScript se descongela donde lo dejaste, en 5 de 12 etapas. Python queda guardado en 2 de 12, tal como está.',
        tlVoltarJs='Volver a JavaScript', tlFicarPy='Seguir en Python',
        tlVoltaTrocandoTit='Guardando Python…',
        tlVoltaTrocandoTxt='Python se congela tal como está, y JavaScript se descongela donde lo dejaste.',
        tlVoltaFimTit='JavaScript de vuelta',
        tlVoltaFimTxt='Sigues donde lo dejaste. Python quedó guardado en 2 de 12 etapas.',
        tlContinuar='Continuar la ruta',
        tlPlanoTit='Python se libera el 12 de noviembre',
        tlPlanoTxt='En Starter estudias un lenguaje a la vez, y el próximo cambio se libera en esa fecha. Hasta entonces, JavaScript sigue abierto donde lo dejaste.',
        tlPlanoPro='En Pro los dos quedan abiertos.',
        tlVerPro='Ver Pro', tlLiberaEm='se libera el 12 nov',
    ),
}
