# Textos da troca de linguagem da trilha (2026-10-04), nos três idiomas da web.
# No Starter a pessoa estuda uma família de linguagem por vez (GET /code/tracks: access "switch" e
# "not_in_plan" com changeAllowedAt; a troca é PUT /code/language-choice). Regra B: voltar no Starter para
# uma linguagem deixada recomeça do zero (a "época" da API); nada é apagado e o Pro vê tudo. Por isso os
# textos nunca prometem voltar de onde parou. Os nomes das trilhas e das etapas vêm da API já no idioma;
# aqui ficam os do exemplo.

TEXTOS = {
    'pt-BR': dict(
        tlRotulo='Troca de linguagem',
        tlJsTrilha='JavaScript do zero', tlPyTrilha='Python do zero',
        tlGuardado='Guardado', tlJsFeitas='5 de 12 etapas', tlPyFeitas='2 de 12 etapas',
        tlJsMeta='5 de 12 etapas · Funções e escopo', tlPyMeta='2 de 12 etapas · Variáveis e tipos',
        tlJsMetaNova='12 etapas · começa em Fundamentos', tlPyMetaNova='12 etapas · começa em Fundamentos',
        tlComeceAqui='comece aqui',
        tlIdaTit='Trocar para Python?', tlVoltaTit='Trocar para JavaScript?',
        tlIdaTxt='No Starter você estuda uma linguagem por vez. JavaScript fica guardado e Python abre do começo.',
        tlVoltaTxt='No Starter você estuda uma linguagem por vez. Python fica guardado e JavaScript abre do começo.',
        tlIdaAviso='Se voltar para JavaScript no Starter, o progresso recomeça do zero. O histórico fica guardado, e no Pro você vê tudo.',
        tlVoltaAviso='Se voltar para Python no Starter, o progresso recomeça do zero. O histórico fica guardado, e no Pro você vê tudo.',
        tlTrocarPy='Trocar para Python', tlTrocarJs='Trocar para JavaScript',
        tlFicarJs='Continuar em JavaScript', tlFicarPy='Continuar em Python',
        tlProLink='No Pro as duas ficam abertas',
        tlIdaTrocandoTit='Guardando JavaScript…', tlVoltaTrocandoTit='Guardando Python…',
        tlIdaTrocandoTxt='JavaScript fica guardado, e Python abre em seguida.',
        tlVoltaTrocandoTxt='Python fica guardado, e JavaScript abre em seguida.',
        tlIdaFimTit='Python aberto', tlVoltaFimTit='JavaScript aberto',
        tlIdaFimTxt='O histórico de JavaScript ficou guardado. Se voltar para JavaScript no Starter, o progresso recomeça do zero.',
        tlVoltaFimTxt='O histórico de Python ficou guardado. Se voltar para Python no Starter, o progresso recomeça do zero.',
        tlComecar='Começar a trilha',
        tlPlanoTit='A troca de linguagem libera em 12 de novembro',
        tlRazao='Esse conteúdo é de Python, e o seu plano estuda uma linguagem por vez.',
        tlPlanoTxt='No Starter você estuda uma linguagem por vez, e a próxima troca fica liberada nessa data. Até lá, JavaScript segue aberto de onde parou.',
        tlPlanoAviso='Quando trocar, JavaScript fica guardado, e voltar para JavaScript no Starter recomeça do zero.',
        tlPlanoPro='No Pro, todas as linguagens ao mesmo tempo.',
        plAgoraNao='Agora não', plConhecerPro='Conhecer o Pro', tlLiberaEm='libera em 12 de nov.',
    ),
    'en-US': dict(
        tlRotulo='Language switch',
        tlJsTrilha='JavaScript from scratch', tlPyTrilha='Python from scratch',
        tlGuardado='Saved', tlJsFeitas='5 of 12 steps', tlPyFeitas='2 of 12 steps',
        tlJsMeta='5 of 12 steps · Functions and scope', tlPyMeta='2 of 12 steps · Variables and types',
        tlJsMetaNova='12 steps · starts at Fundamentals', tlPyMetaNova='12 steps · starts at Fundamentals',
        tlComeceAqui='start here',
        tlIdaTit='Switch to Python?', tlVoltaTit='Switch to JavaScript?',
        tlIdaTxt='On Starter you study one language at a time. JavaScript is saved and Python opens from the start.',
        tlVoltaTxt='On Starter you study one language at a time. Python is saved and JavaScript opens from the start.',
        tlIdaAviso='If you go back to JavaScript on Starter, your progress starts over from zero. Your history stays saved, and on Pro you see all of it.',
        tlVoltaAviso='If you go back to Python on Starter, your progress starts over from zero. Your history stays saved, and on Pro you see all of it.',
        tlTrocarPy='Switch to Python', tlTrocarJs='Switch to JavaScript',
        tlFicarJs='Stay on JavaScript', tlFicarPy='Stay on Python',
        tlProLink='On Pro both stay open',
        tlIdaTrocandoTit='Saving JavaScript…', tlVoltaTrocandoTit='Saving Python…',
        tlIdaTrocandoTxt='JavaScript is saved, and Python opens next.',
        tlVoltaTrocandoTxt='Python is saved, and JavaScript opens next.',
        tlIdaFimTit='Python is open', tlVoltaFimTit='JavaScript is open',
        tlIdaFimTxt='Your JavaScript history was saved. If you go back to JavaScript on Starter, your progress starts over from zero.',
        tlVoltaFimTxt='Your Python history was saved. If you go back to Python on Starter, your progress starts over from zero.',
        tlComecar='Start the track',
        tlPlanoTit='Language switching opens on November 12',
        tlRazao='This content is in Python, and your plan studies one language at a time.',
        tlPlanoTxt='On Starter you study one language at a time, and your next switch opens on that date. Until then, JavaScript stays open where you left off.',
        tlPlanoAviso='When you switch, JavaScript is saved, and going back to JavaScript on Starter starts over from zero.',
        tlPlanoPro='On Pro, every language at the same time.',
        plAgoraNao='Not now', plConhecerPro='See Pro', tlLiberaEm='opens Nov 12',
    ),
    'es-ES': dict(
        tlRotulo='Cambio de lenguaje',
        tlJsTrilha='JavaScript desde cero', tlPyTrilha='Python desde cero',
        tlGuardado='Guardado', tlJsFeitas='5 de 12 etapas', tlPyFeitas='2 de 12 etapas',
        tlJsMeta='5 de 12 etapas · Funciones y alcance', tlPyMeta='2 de 12 etapas · Variables y tipos',
        tlJsMetaNova='12 etapas · empieza en Fundamentos', tlPyMetaNova='12 etapas · empieza en Fundamentos',
        tlComeceAqui='empieza aquí',
        tlIdaTit='¿Cambiar a Python?', tlVoltaTit='¿Cambiar a JavaScript?',
        tlIdaTxt='En Starter estudias un lenguaje a la vez. JavaScript queda guardado y Python se abre desde el principio.',
        tlVoltaTxt='En Starter estudias un lenguaje a la vez. Python queda guardado y JavaScript se abre desde el principio.',
        tlIdaAviso='Si vuelves a JavaScript en Starter, el progreso empieza de cero. El historial queda guardado, y en Pro lo ves todo.',
        tlVoltaAviso='Si vuelves a Python en Starter, el progreso empieza de cero. El historial queda guardado, y en Pro lo ves todo.',
        tlTrocarPy='Cambiar a Python', tlTrocarJs='Cambiar a JavaScript',
        tlFicarJs='Seguir en JavaScript', tlFicarPy='Seguir en Python',
        tlProLink='En Pro los dos quedan abiertos',
        tlIdaTrocandoTit='Guardando JavaScript…', tlVoltaTrocandoTit='Guardando Python…',
        tlIdaTrocandoTxt='JavaScript queda guardado, y Python se abre enseguida.',
        tlVoltaTrocandoTxt='Python queda guardado, y JavaScript se abre enseguida.',
        tlIdaFimTit='Python abierto', tlVoltaFimTit='JavaScript abierto',
        tlIdaFimTxt='El historial de JavaScript quedó guardado. Si vuelves a JavaScript en Starter, el progreso empieza de cero.',
        tlVoltaFimTxt='El historial de Python quedó guardado. Si vuelves a Python en Starter, el progreso empieza de cero.',
        tlComecar='Empezar la ruta',
        tlPlanoTit='El cambio de lenguaje se libera el 12 de noviembre',
        tlRazao='Este contenido es de Python, y tu plan estudia un lenguaje a la vez.',
        tlPlanoTxt='En Starter estudias un lenguaje a la vez, y el próximo cambio se libera en esa fecha. Hasta entonces, JavaScript sigue abierto donde lo dejaste.',
        tlPlanoAviso='Cuando cambies, JavaScript queda guardado, y volver a JavaScript en Starter empieza de cero.',
        tlPlanoPro='En Pro, todos los lenguajes al mismo tiempo.',
        plAgoraNao='Ahora no', plConhecerPro='Conocer Pro', tlLiberaEm='se libera el 12 nov',
    ),
}
