# Textos da escolha obrigatória de plano (2026-10-03), nos três idiomas da web. Regra: conta nova que
# terminou o onboarding e ainda não escolheu recebe 403 PLAN_CHOICE_REQUIRED, e o app segura a pessoa
# em /plans. Três opções: Starter, o teste do Pro (sem cartão) e o Pro pago. Os nomes finais vêm da API.

TEXTOS = {
    'pt-BR': dict(
        periodo='Período de cobrança', mensal='Mensal', anual='Anual', economia='-17%',
        escTitulo='Escolha seu plano',
        escSub='Comece pelo teste do Pro, fique no Starter ou assine direto. Dá para trocar depois.',
        faltaEscolher='Falta escolher',
        faltaTxt='O Code abre assim que você escolher um plano. Nada é cobrado sem você assinar.',
        ariaStarter='Plano Starter', ariaTeste='Teste grátis do Pro', ariaPro='Plano Pro',
        gratis='Grátis', semCartao='para sempre, sem cartão', preco='R$ 49,90', porMes='/mês', porAno='ou R$ 499 por ano',
        testeSelo='teste grátis', testeNota='por 14 dias, sem cartão', recomendado='Recomendado',
        s1='As primeiras etapas de cada trilha', s2='Exercícios com testes automáticos', s3='A Evolução do seu nível',
        s4='Limite mensal de exercícios', aDefinir='a definir',
        t1='Tudo do Pro durante o teste', t2='Sem cobrança: o teste acaba sozinho', t3='No fim, você escolhe entre Starter e Pro',
        p1='Trilhas completas, com todas as etapas', p2='O Peer revisando cada solução', p3='A Evolução com histórico e trajetória',
        p4='Exercícios de arquitetura',
        ficarStarter='Ficar no Starter', testarPro='Testar o Pro grátis', assinarPro='Assinar o Pro',
        r1='O teste dura 14 dias e não pede cartão.',
        r2='Escolher o Starter durante o teste encerra o teste.',
        r3='Assinou? Cancela quando quiser, e o Pro fica até o fim do período pago.',
    ),
    'en-US': dict(
        periodo='Billing period', mensal='Monthly', anual='Yearly', economia='-17%',
        escTitulo='Choose your plan',
        escSub='Start with the Pro trial, stay on Starter or subscribe right away. You can switch later.',
        faltaEscolher='Choice needed',
        faltaTxt='Code opens as soon as you choose a plan. Nothing is charged unless you subscribe.',
        ariaStarter='Starter plan', ariaTeste='Free Pro trial', ariaPro='Pro plan',
        gratis='Free', semCartao='forever, no card', preco='R$49.90', porMes='/month', porAno='or R$499 a year',
        testeSelo='free trial', testeNota='for 14 days, no card', recomendado='Recommended',
        s1='The first steps of every track', s2='Exercises with automated tests', s3='Progress on your level',
        s4='Monthly exercise limit', aDefinir='to be defined',
        t1='Everything in Pro during the trial', t2='No charge: the trial just ends', t3='At the end, you choose Starter or Pro',
        p1='Full tracks, with every step', p2='The Peer reviewing each solution', p3='Progress with history and trajectory',
        p4='Architecture exercises',
        ficarStarter='Stay on Starter', testarPro='Try Pro for free', assinarPro='Subscribe to Pro',
        r1='The trial lasts 14 days and asks for no card.',
        r2='Choosing Starter during the trial ends the trial.',
        r3='Subscribed? Cancel anytime, and Pro stays until the end of the paid period.',
    ),
    'es-ES': dict(
        periodo='Periodo de facturación', mensal='Mensual', anual='Anual', economia='-17%',
        escTitulo='Elige tu plan',
        escSub='Empieza con la prueba de Pro, quédate en Starter o suscríbete directamente. Puedes cambiar después.',
        faltaEscolher='Falta elegir',
        faltaTxt='Code se abre en cuanto eliges un plan. No se cobra nada sin que te suscribas.',
        ariaStarter='Plan Starter', ariaTeste='Prueba gratis de Pro', ariaPro='Plan Pro',
        gratis='Gratis', semCartao='para siempre, sin tarjeta', preco='R$ 49,90', porMes='/mes', porAno='o R$ 499 al año',
        testeSelo='prueba gratis', testeNota='por 14 días, sin tarjeta', recomendado='Recomendado',
        s1='Las primeras etapas de cada ruta', s2='Ejercicios con pruebas automáticas', s3='La evolución de tu nivel',
        s4='Límite mensual de ejercicios', aDefinir='por definir',
        t1='Todo lo de Pro durante la prueba', t2='Sin cobro: la prueba termina sola', t3='Al final, eliges entre Starter y Pro',
        p1='Rutas completas, con todas las etapas', p2='El Peer revisando cada solución', p3='La evolución con historial y trayectoria',
        p4='Ejercicios de arquitectura',
        ficarStarter='Quedarme en Starter', testarPro='Probar Pro gratis', assinarPro='Suscribirme a Pro',
        r1='La prueba dura 14 días y no pide tarjeta.',
        r2='Elegir Starter durante la prueba termina la prueba.',
        r3='¿Te suscribiste? Cancela cuando quieras, y Pro se mantiene hasta el final del periodo pagado.',
    ),
}
