# Textos da execução passo a passo e do "Você sabia?" (2026-10-03), nos três idiomas da web. O
# conteúdo da lição (o título, o texto, o código e os passos) e os "Você sabia?" vêm do pacote de
# conteúdo (muriki-content: lessons/js.variables.md, catalog/insights/js.yaml), no idioma da pessoa.

TEXTOS = {
    'pt-BR': dict(
        licaoTit='Variáveis e reatribuição', licaoDesc='A lição da skill, para ler sem sair do exercício.',
        licaoSecao='Exemplo resolvido',
        licaoTxt='Uma variável guarda o valor do momento. Copiar uma variável para outra copia o valor que ela tem naquele instante; as duas não ficam ligadas. Acompanhe linha a linha.',
        execTit='Passo a passo', passo='passo', de='de', fim='fim',
        variaveis='Variáveis', console_='Console', semVariaveis='nenhuma ainda', semSaida='nada impresso ainda',
        mudou='mudou', nova='nova',
        anterior='Anterior', proximo='Próximo', reiniciar='Recomeçar', tocar='Tocar', pausar='Pausar',
        voceSabia='Você sabia?',
        vs1Tit='const não congela o objeto',
        vs1a='const impede só que a variável receba outro valor. O objeto que ela guarda continua mudando:',
        vs1b='Quem recebe esse objeto e o altera muda o mesmo objeto que você tem. Para não mexer no original, crie um objeto novo com as mudanças.',
        vs2Tit='== converte antes de comparar',
        vs2a='O == converte os dois lados para um mesmo tipo antes de comparar, e as regras dessa conversão surpreendem:',
        vs2b='O === compara sem converter: valores de tipos diferentes nunca são iguais. Use === e !==, e converta você mesmo quando precisar, com Number(texto).',
        guiaTit='Guia de sintaxe', guiaDesc='O que a linguagem oferece, com o recurso de cada exemplo.',
        guiaGrupo='Comparações', recIgual='Igualdade estrita', recIgualTxt='Compara valor e tipo, sem converter.',
        recMaior='Maior e menor', recMaiorTxt='Compara números; com textos, compara pela ordem das letras.',
        verNaLicao='Ver na lição',
        peerVsTxt='Na linha 4 você usou ==. Ele converte os dois lados antes de comparar, então "" == 0 dá true.',
        lerNoGuia='Ler no guia',
    ),
    'en-US': dict(
        licaoTit='Variables and reassignment', licaoDesc='The skill lesson, to read without leaving the exercise.',
        licaoSecao='Worked example',
        licaoTxt='A variable holds the value of the moment. Copying a variable to another copies the value it has at that instant; the two are not linked. Follow it line by line.',
        execTit='Step by step', passo='step', de='of', fim='end',
        variaveis='Variables', console_='Console', semVariaveis='none yet', semSaida='nothing printed yet',
        mudou='changed', nova='new',
        anterior='Previous', proximo='Next', reiniciar='Start over', tocar='Play', pausar='Pause',
        voceSabia='Did you know?',
        vs1Tit='const does not freeze the object',
        vs1a='const only stops the variable from getting another value. The object it holds keeps changing:',
        vs1b='Whoever receives that object and changes it changes the same object you have. To leave the original alone, create a new object with the changes.',
        vs2Tit='== converts before comparing',
        vs2a='== converts both sides to the same type before comparing, and the rules of that conversion are surprising:',
        vs2b='=== compares without converting: values of different types are never equal. Use === and !==, and convert yourself when you need to, with Number(text).',
        guiaTit='Syntax guide', guiaDesc='What the language offers, with the feature behind each example.',
        guiaGrupo='Comparisons', recIgual='Strict equality', recIgualTxt='Compares value and type, without converting.',
        recMaior='Greater and less than', recMaiorTxt='Compares numbers; with strings, compares by letter order.',
        verNaLicao='See it in the lesson',
        peerVsTxt='On line 4 you used ==. It converts both sides before comparing, so "" == 0 is true.',
        lerNoGuia='Read it in the guide',
    ),
    'es-ES': dict(
        licaoTit='Variables y reasignación', licaoDesc='La lección de la skill, para leer sin salir del ejercicio.',
        licaoSecao='Ejemplo resuelto',
        licaoTxt='Una variable guarda el valor del momento. Copiar una variable a otra copia el valor que tiene en ese instante; las dos no quedan ligadas. Síguelo línea a línea.',
        execTit='Paso a paso', passo='paso', de='de', fim='fin',
        variaveis='Variables', console_='Consola', semVariaveis='ninguna aún', semSaida='nada impreso aún',
        mudou='cambió', nova='nueva',
        anterior='Anterior', proximo='Siguiente', reiniciar='Empezar de nuevo', tocar='Reproducir', pausar='Pausar',
        voceSabia='¿Sabías que…?',
        vs1Tit='const no congela el objeto',
        vs1a='const solo impide que la variable reciba otro valor. El objeto que guarda sigue cambiando:',
        vs1b='Quien recibe ese objeto y lo cambia cambia el mismo objeto que tú tienes. Para no tocar el original, crea un objeto nuevo con los cambios.',
        vs2Tit='== convierte antes de comparar',
        vs2a='El == convierte los dos lados a un mismo tipo antes de comparar, y las reglas de esa conversión sorprenden:',
        vs2b='El === compara sin convertir: valores de tipos distintos nunca son iguales. Usa === y !==, y convierte tú mismo cuando haga falta, con Number(texto).',
        guiaTit='Guía de sintaxis', guiaDesc='Lo que ofrece el lenguaje, con el recurso detrás de cada ejemplo.',
        guiaGrupo='Comparaciones', recIgual='Igualdad estricta', recIgualTxt='Compara valor y tipo, sin convertir.',
        recMaior='Mayor y menor', recMaiorTxt='Compara números; con textos, compara por el orden de las letras.',
        verNaLicao='Ver en la lección',
        peerVsTxt='En la línea 4 usaste ==. Convierte los dos lados antes de comparar, así que "" == 0 da true.',
        lerNoGuia='Leer en la guía',
    ),
}
