# Textos da conta no contrato da muriki-api: criar conta sem senha (nome, email e captcha; a senha
# vem pelo link do email), criar e redefinir senha (12 a 128 caracteres, não pode estar em
# vazamentos), esqueci a senha (202 sempre, exista ou não a conta) e o segundo fator com o código
# de backup. Somam-se ao ACESSO da tela de entrada.

CONTA = {
    'pt-BR': dict(
        captcha='Verificação anti-robô (Turnstile, da Cloudflare)', captchaOk='Verificado',
        criarEnviar='Criar conta',
        enviadoRotulo='Confira seu email', enviadoA='Mandamos um link', enviadoB='para o seu email.',
        enviadoSub='Abra o link que enviamos para', enviadoTxt='para criar a sua senha. Ele vale por 24 horas.',
        reenviar='Reenviar o email', outroEmail='Usar outro email', naoChegou='Não chegou? Olhe o spam e as promoções.',
        criarSenhaRotulo='Criar senha', criarSenhaA='Falta só', criarSenhaB='a sua senha.',
        criarSenhaSub='Para a conta', redefinirRotulo='Nova senha', redefinirA='Escolha uma', redefinirB='senha nova.',
        novaSenha='Senha nova', novaSenhaPh='Pelo menos 12 caracteres', req12='12 caracteres',
        salvarSenha='Salvar senha', depoisEntrar='Depois você entra com o seu email e a senha nova.',
        vazada='Essa senha apareceu em um vazamento de dados. Escolha outra.',
        expiradoTit='Este link não vale mais', expiradoTxt='Links de senha valem por 24 horas e só uma vez. Peça um novo.',
        pedirNovo='Pedir um novo link',
        esqueciRotulo='Esqueci a senha', esqueciA='Acontece.', esqueciB='Vamos trocar.',
        esqueciSub='Diga o email da sua conta e mandamos um link para criar uma senha nova.',
        enviarLink='Enviar link', voltarEntrar='Voltar para entrar',
        esqueciEnviadoA='Se a conta existir,', esqueciEnviadoB='o link chegou.',
        esqueciEnviadoTxt='Se existir uma conta com esse email, ele recebe um link para criar uma senha nova. O link vale por 24 horas.',
        codigoRotulo='Segundo fator', codigoA='Mais um', codigoB='passo.',
        codigoSub='Digite o código de 6 dígitos do seu app autenticador.',
        codigoLegenda='Código', backupLegenda='Código de backup', backupPh='xxxx-xxxx',
        usarBackup='Usar um código de backup', usarApp='Usar o app autenticador',
        backupNota='Cada código de backup vale uma vez. Você recebeu dez quando ativou o segundo fator.',
        verificar='Verificar', codigoInvalido='Código inválido. Confira e tente de novo.',
        naoConsegue='Sem acesso ao app nem aos códigos? Fale com o suporte.',
    ),
    'en-US': dict(
        captcha='Bot check (Turnstile, by Cloudflare)', captchaOk='Verified',
        criarEnviar='Create account',
        enviadoRotulo='Check your email', enviadoA='We sent a link', enviadoB='to your email.',
        enviadoSub='Open the link we sent to', enviadoTxt='to create your password. It’s valid for 24 hours.',
        reenviar='Resend the email', outroEmail='Use another email', naoChegou='Didn’t get it? Check spam and promotions.',
        criarSenhaRotulo='Create password', criarSenhaA='Just one', criarSenhaB='more thing.',
        criarSenhaSub='For the account', redefinirRotulo='New password', redefinirA='Choose a', redefinirB='new password.',
        novaSenha='New password', novaSenhaPh='At least 12 characters', req12='12 characters',
        salvarSenha='Save password', depoisEntrar='Then you sign in with your email and the new password.',
        vazada='This password showed up in a data breach. Choose another one.',
        expiradoTit='This link no longer works', expiradoTxt='Password links are valid for 24 hours and only once. Ask for a new one.',
        pedirNovo='Ask for a new link',
        esqueciRotulo='Forgot password', esqueciA='It happens.', esqueciB='Let’s reset it.',
        esqueciSub='Tell us your account email and we’ll send a link to create a new password.',
        enviarLink='Send link', voltarEntrar='Back to sign in',
        esqueciEnviadoA='If the account exists,', esqueciEnviadoB='the link is on its way.',
        esqueciEnviadoTxt='If there’s an account with this email, it gets a link to create a new password. The link is valid for 24 hours.',
        codigoRotulo='Second factor', codigoA='One more', codigoB='step.',
        codigoSub='Enter the 6-digit code from your authenticator app.',
        codigoLegenda='Code', backupLegenda='Backup code', backupPh='xxxx-xxxx',
        usarBackup='Use a backup code', usarApp='Use the authenticator app',
        backupNota='Each backup code works once. You got ten when you turned on the second factor.',
        verificar='Verify', codigoInvalido='Invalid code. Check it and try again.',
        naoConsegue='No access to the app or the codes? Contact support.',
    ),
    'es-ES': dict(
        captcha='Verificación anti-bots (Turnstile, de Cloudflare)', captchaOk='Verificado',
        criarEnviar='Crear cuenta',
        enviadoRotulo='Revisa tu email', enviadoA='Te enviamos un enlace', enviadoB='a tu email.',
        enviadoSub='Abre el enlace que enviamos a', enviadoTxt='para crear tu contraseña. Vale 24 horas.',
        reenviar='Reenviar el email', outroEmail='Usar otro email', naoChegou='¿No te llegó? Mira en spam y promociones.',
        criarSenhaRotulo='Crear contraseña', criarSenhaA='Solo falta', criarSenhaB='tu contraseña.',
        criarSenhaSub='Para la cuenta', redefinirRotulo='Nueva contraseña', redefinirA='Elige una', redefinirB='contraseña nueva.',
        novaSenha='Contraseña nueva', novaSenhaPh='Al menos 12 caracteres', req12='12 caracteres',
        salvarSenha='Guardar contraseña', depoisEntrar='Después entras con tu email y la contraseña nueva.',
        vazada='Esta contraseña apareció en una filtración de datos. Elige otra.',
        expiradoTit='Este enlace ya no vale', expiradoTxt='Los enlaces de contraseña valen 24 horas y una sola vez. Pide uno nuevo.',
        pedirNovo='Pedir un enlace nuevo',
        esqueciRotulo='Olvidé la contraseña', esqueciA='Pasa.', esqueciB='Vamos a cambiarla.',
        esqueciSub='Dinos el email de tu cuenta y te enviamos un enlace para crear una contraseña nueva.',
        enviarLink='Enviar enlace', voltarEntrar='Volver a entrar',
        esqueciEnviadoA='Si la cuenta existe,', esqueciEnviadoB='el enlace ya salió.',
        esqueciEnviadoTxt='Si hay una cuenta con ese email, recibe un enlace para crear una contraseña nueva. Vale 24 horas.',
        codigoRotulo='Segundo factor', codigoA='Un paso', codigoB='más.',
        codigoSub='Escribe el código de 6 dígitos de tu app de autenticación.',
        codigoLegenda='Código', backupLegenda='Código de respaldo', backupPh='xxxx-xxxx',
        usarBackup='Usar un código de respaldo', usarApp='Usar la app de autenticación',
        backupNota='Cada código de respaldo vale una vez. Recibiste diez al activar el segundo factor.',
        verificar='Verificar', codigoInvalido='Código inválido. Revísalo e inténtalo de nuevo.',
        naoConsegue='¿Sin acceso a la app ni a los códigos? Habla con soporte.',
    ),
}
