IDIOMAS = ['pt-BR', 'en-US', 'es-ES']

COMUM = {
    'pt-BR': dict(
        lang='pt-BR', idiomaCurto='PT', idiomaNome='Português', trocarIdioma='Idioma: português. Trocar idioma',
        paraEscuro='Tema claro. Mudar para o escuro', paraClaro='Tema escuro. Mudar para o claro',
        evolucao='Evolução', trilhas='Trilhas', exercicios='Exercícios', avaliacoes='Avaliações',
        peer='Peer na IDE', plano='Plano', trilhaAria='Trilha', aprender='Aprender',
        contaMuriki='conta Muriki', trocarProduto='Trocar de produto Muriki', config='Configurações',
        pleno='Pleno', playground='Playground',
    ),
    'en-US': dict(
        lang='en-US', idiomaCurto='EN', idiomaNome='English', trocarIdioma='Language: English. Change language',
        paraEscuro='Light theme. Switch to dark', paraClaro='Dark theme. Switch to light',
        evolucao='Progress', trilhas='Tracks', exercicios='Exercises', avaliacoes='Evaluations',
        peer='Peer in your IDE', plano='Plan', trilhaAria='Breadcrumb', aprender='Learn',
        contaMuriki='Muriki account', trocarProduto='Switch Muriki product', config='Settings',
        pleno='Mid-level', playground='Playground',
    ),
    'es-ES': dict(
        lang='es-ES', idiomaCurto='ES', idiomaNome='Español', trocarIdioma='Idioma: español. Cambiar idioma',
        paraEscuro='Tema claro. Cambiar a oscuro', paraClaro='Tema oscuro. Cambiar a claro',
        evolucao='Evolución', trilhas='Rutas', exercicios='Ejercicios', avaliacoes='Evaluaciones',
        peer='Peer en el IDE', plano='Plan', trilhaAria='Ruta de navegación', aprender='Aprender',
        contaMuriki='cuenta Muriki', trocarProduto='Cambiar de producto Muriki', config='Ajustes',
        pleno='Intermedio', playground='Playground',
    ),
}

EVOLUCAO = {
    'pt-BR': dict(
        titulo='Seu perfil de competência',
        sub='Calculado a partir de 219 evidências. O declarado é o seu ponto de partida; o observado só muda com '
            'evidência forte, e nunca por um exercício ruim.',
        trajetoria='Trajetória', comoMedido='Como o nível é medido', competencias='Competências',
        colComp='Competência', colEscala='Escala', colDecl='Declarado', colObs='Observado', colEstado='Estado',
        grupoLing='Linguagens', grupoEng='Engenharia',
        estConfirmado='confirmado', estDeclarado='declarado', estNaoUso='não uso', aConfirmar='a confirmar', emProgresso='em progresso',
        confirmam3='3 exercícios confirmam', confirmam2='2 exercícios confirmam', doisDeTres='2 de 3 exercícios', adicionar='Adicionar',
        legObs='observado', legDecl='declarado', legProg='em progresso',
        proximoPasso='Próximo passo', confirma='confirma', proxTitulo='Slots com relógio injetado',
        proxTxt='O primeiro dos 3 exercícios de Senior que confirmam Testing. Cobre o que ficou de fora em agenda-slots: '
                'o tempo como parâmetro e a virada do dia em UTC-3.',
        comecar='Começar', verOsTres='Ver os 3',
        evRecente='Evidência recente', verTodas='Ver todas',
        fonteExercicio='exercício', fonteExplicacao='explicação', fontePeer='Peer', fontePlayground='playground',
        pesoForte='forte', pesoLeve='leve',
        ev1='Corrigiu um teste depois da pergunta do Peer', ev2='Tratou a linha vazia de um CSV em Python',
        ev3='Solução de agenda-slots: rubrica 3 de 5', ev4='Explicação de agenda-slots: parcial',
        q1='há 14 min', q2='há 2 h', q3='ontem', q4='ontem',
        trajTit='Trajetória em Testing', trajTxt='Asserts por teste nas suas últimas 5 soluções, contra as 5 anteriores.',
        trajAntes='1,4', trajDepois='2,6', trajLink='Ver a solução de junho ao lado da de hoje',
    ),
    'en-US': dict(
        titulo='Your competency profile',
        sub='Calculated from 219 pieces of evidence. Declared is your starting point; observed only changes with '
            'strong evidence, and never because of one bad exercise.',
        trajetoria='Trajectory', comoMedido='How the level is measured', competencias='Competencies',
        colComp='Competency', colEscala='Scale', colDecl='Declared', colObs='Observed', colEstado='Status',
        grupoLing='Languages', grupoEng='Engineering',
        estConfirmado='confirmed', estDeclarado='declared', estNaoUso='don’t use', aConfirmar='to confirm', emProgresso='in progress',
        confirmam3='3 exercises would confirm', confirmam2='2 exercises would confirm', doisDeTres='2 of 3 exercises', adicionar='Add',
        legObs='observed', legDecl='declared', legProg='in progress',
        proximoPasso='Next step', confirma='confirms', proxTitulo='Slots with an injected clock',
        proxTxt='The first of 3 Senior exercises that confirm Testing. It covers what agenda-slots left out: '
                'time as a parameter and the day rolling over in UTC-3.',
        comecar='Start', verOsTres='See all 3',
        evRecente='Recent evidence', verTodas='See all',
        fonteExercicio='exercise', fonteExplicacao='explanation', fontePeer='Peer', fontePlayground='playground',
        pesoForte='strong', pesoLeve='light',
        ev1='Fixed a test after the Peer’s question', ev2='Handled the empty row of a CSV in Python',
        ev3='agenda-slots solution: rubric 3 of 5', ev4='agenda-slots explanation: partial',
        q1='14 min ago', q2='2 h ago', q3='yesterday', q4='yesterday',
        trajTit='Trajectory in Testing', trajTxt='Asserts per test in your last 5 solutions, compared with the 5 before.',
        trajAntes='1.4', trajDepois='2.6', trajLink='See June’s solution next to today’s',
    ),
    'es-ES': dict(
        titulo='Tu perfil de competencias',
        sub='Calculado a partir de 219 evidencias. El declarado es tu punto de partida; el observado solo cambia con '
            'evidencia fuerte, y nunca por un ejercicio malo.',
        trajetoria='Trayectoria', comoMedido='Cómo se mide el nivel', competencias='Competencias',
        colComp='Competencia', colEscala='Escala', colDecl='Declarado', colObs='Observado', colEstado='Estado',
        grupoLing='Lenguajes', grupoEng='Ingeniería',
        estConfirmado='confirmado', estDeclarado='declarado', estNaoUso='no lo uso', aConfirmar='por confirmar', emProgresso='en progreso',
        confirmam3='3 ejercicios lo confirman', confirmam2='2 ejercicios lo confirman', doisDeTres='2 de 3 ejercicios', adicionar='Añadir',
        legObs='observado', legDecl='declarado', legProg='en progreso',
        proximoPasso='Siguiente paso', confirma='confirma', proxTitulo='Slots con reloj inyectado',
        proxTxt='El primero de los 3 ejercicios de Senior que confirman Testing. Cubre lo que agenda-slots dejó fuera: '
                'el tiempo como parámetro y el cambio de día en UTC-3.',
        comecar='Empezar', verOsTres='Ver los 3',
        evRecente='Evidencia reciente', verTodas='Ver todas',
        fonteExercicio='ejercicio', fonteExplicacao='explicación', fontePeer='Peer', fontePlayground='playground',
        pesoForte='fuerte', pesoLeve='ligera',
        ev1='Corrigió una prueba tras la pregunta del Peer', ev2='Trató la fila vacía de un CSV en Python',
        ev3='Solución de agenda-slots: rúbrica 3 de 5', ev4='Explicación de agenda-slots: parcial',
        q1='hace 14 min', q2='hace 2 h', q3='ayer', q4='ayer',
        trajTit='Trayectoria en Testing', trajTxt='Asserts por prueba en tus últimas 5 soluciones, frente a las 5 anteriores.',
        trajAntes='1,4', trajDepois='2,6', trajLink='Ver la solución de junio junto a la de hoy',
    ),
}

AVALIACAO = {
    'pt-BR': dict(
        titulo='Avaliação de agenda-slots', enviada='enviada ontem, 18:42', verSolucao='Ver a solução enviada',
        rubricaAria='Rubrica', rubricaTesting='Rubrica de Testing · Senior', nivelSenior='nível Senior', tresDeCinco='3 de 5', atendidos='critérios atendidos',
        c1='O teste falha pelo motivo certo', c2='Um comportamento por teste',
        c3='O nome do teste descreve o comportamento', c4='Isola dependências de tempo e rede',
        c5='Cobre as bordas: vazio, limite e fuso',
        atende='atende', parcial='parcial', naoAtende='não atende',
        oQueMuda='O que muda',
        efPerfil='Perfil', efPerfilTxt='Ainda não conta para confirmar Senior: a rubrica de Senior pede 4 de 5. Pleno segue confirmado.',
        efTrilhas='Trilhas', efTrilhasTxt='O próximo exercício de confirmação cobre o que faltou: o tempo como parâmetro e a virada do dia em UTC-3.',
        efTraj='Trajetória', efTrajTxt='Asserts por teste: 2,6 nas últimas 5 soluções, contra 1,4 nas 5 anteriores.',
        explicacaoTit='Sua explicação', perguntaEx='Como você garantiu que os slots não dependem da hora em que o teste roda?',
        respostaEx='“Criei o relogioFixo para os testes do fim do dia, que eram os que falhavam.”',
        porqueEx='Você achou a causa, o relógio, mas tratou o sintoma: dois testes ganharam relogioFixo e gerarSlots continua lendo Date.now(). O próximo passo é levar esse entendimento para o contrato da função.',
        irProximo='Ir para o próximo passo', porQue='Por que essa nota',
        p1='Seus testes dizem o que esperam, e cada um falha por um motivo só. É o que mais pesa nesta rubrica, '
           'e por isso três critérios foram atendidos de cara.',
        p2a='O que segurou a nota foi o tempo.', p2b='lê',
        p2c='direto, então o teste que passa às 14h falha às 23h59. Você chegou perto quando criou',
        p2d=', mas ele entrou em só dois dos cinco testes.',
        p3='Faltou também a borda do fuso: nenhum teste roda o dia virando em UTC-3.',
        ondeOlhar='Onde olhar',
    ),
    'en-US': dict(
        titulo='Evaluation of agenda-slots', enviada='submitted yesterday, 6:42 PM', verSolucao='See the submitted solution',
        rubricaAria='Rubric', rubricaTesting='Testing rubric · Senior', nivelSenior='Senior level', tresDeCinco='3 of 5', atendidos='criteria met',
        c1='The test fails for the right reason', c2='One behavior per test',
        c3='The test name describes the behavior', c4='Isolates time and network dependencies',
        c5='Covers the edges: empty, limit and time zone',
        atende='met', parcial='partial', naoAtende='not met',
        oQueMuda='What changes',
        efPerfil='Profile', efPerfilTxt='It doesn’t count toward confirming Senior yet: the Senior rubric asks for 4 of 5. Mid-level stays confirmed.',
        efTrilhas='Tracks', efTrilhasTxt='The next confirming exercise covers what was missing: time as a parameter and the day rolling over in UTC-3.',
        efTraj='Trajectory', efTrajTxt='Asserts per test: 2.6 in your last 5 solutions, against 1.4 in the 5 before.',
        explicacaoTit='Your explanation', perguntaEx='How did you make sure the slots don’t depend on when the test runs?',
        respostaEx='“I created relogioFixo for the end-of-day tests, which were the ones failing.”',
        porqueEx='You found the cause, the clock, but treated the symptom: two tests got relogioFixo and gerarSlots still reads Date.now(). The next step is taking that understanding into the function’s contract.',
        irProximo='Go to the next step', porQue='Why this grade',
        p1='Your tests say what they expect, and each one fails for a single reason. That weighs the most in this rubric, '
           'which is why three criteria were met right away.',
        p2a='What held the grade back was time.', p2b='reads',
        p2c='directly, so the test that passes at 2 PM fails at 11:59 PM. You got close when you created',
        p2d=', but it only made it into two of the five tests.',
        p3='The time zone edge is missing too: no test runs the day rolling over in UTC-3.',
        ondeOlhar='Where to look',
    ),
    'es-ES': dict(
        titulo='Evaluación de agenda-slots', enviada='enviada ayer, 18:42', verSolucao='Ver la solución enviada',
        rubricaAria='Rúbrica', rubricaTesting='Rúbrica de Testing · Senior', nivelSenior='nivel Senior', tresDeCinco='3 de 5', atendidos='criterios cumplidos',
        c1='La prueba falla por el motivo correcto', c2='Un comportamiento por prueba',
        c3='El nombre de la prueba describe el comportamiento', c4='Aísla las dependencias de tiempo y red',
        c5='Cubre los bordes: vacío, límite y zona horaria',
        atende='cumple', parcial='parcial', naoAtende='no cumple',
        oQueMuda='Qué cambia',
        efPerfil='Perfil', efPerfilTxt='Todavía no cuenta para confirmar Senior: la rúbrica de Senior pide 4 de 5. Intermedio sigue confirmado.',
        efTrilhas='Rutas', efTrilhasTxt='El siguiente ejercicio de confirmación cubre lo que faltó: el tiempo como parámetro y el cambio de día en UTC-3.',
        efTraj='Trayectoria', efTrajTxt='Asserts por prueba: 2,6 en las últimas 5 soluciones, frente a 1,4 en las 5 anteriores.',
        explicacaoTit='Tu explicación', perguntaEx='¿Cómo te aseguraste de que los slots no dependen de la hora a la que se ejecuta la prueba?',
        respostaEx='“Creé relogioFixo para las pruebas del final del día, que eran las que fallaban.”',
        porqueEx='Has encontrado la causa, el reloj, pero has tratado el síntoma: dos pruebas recibieron relogioFixo y gerarSlots sigue leyendo Date.now(). El siguiente paso es llevar ese entendimiento al contrato de la función.',
        irProximo='Ir al siguiente paso', porQue='Por qué esta nota',
        p1='Tus pruebas dicen lo que esperan, y cada una falla por un solo motivo. Es lo que más pesa en esta rúbrica, '
           'y por eso tres criterios se cumplieron de entrada.',
        p2a='Lo que frenó la nota fue el tiempo.', p2b='lee',
        p2c='directamente, así que la prueba que pasa a las 14:00 falla a las 23:59. Te acercaste cuando creaste',
        p2d=', pero solo entró en dos de las cinco pruebas.',
        p3='También faltó el borde de la zona horaria: ninguna prueba ejecuta el cambio de día en UTC-3.',
        ondeOlhar='Dónde mirar',
    ),
}

CONECTAR = {
    'pt-BR': dict(
        rotulo='Conectar IDE', titulo='Confirme o código que aparece na sua IDE',
        pedidoA='Pedido feito há 20 segundos por', pedidoIde='VS Code no macOS',
        pedidoB='. Não se digita senha dentro da IDE.',
        vaiPoder='O Peer vai poder', pode1='Ler o trecho em volta dos eventos, nos projetos em que você ligar',
        pode2='Registrar evidência no seu perfil do Code',
        nunca='Nunca vai poder', nunca1='Ver senha, pagamento ou dados do Platform',
        nunca2='Ler .env, secrets ou arquivos ignorados pelo Git',
        conectar='Conectar esta IDE', naoFuiEu='Não fui eu',
        dispositivos='Dispositivos conectados', jaConectadas='Já conectadas',
        cadaIde='Cada IDE é um dispositivo da sua conta',
        cursorSub='conectado há 12 dias · último uso ontem', desconectar='Desconectar',
    ),
    'en-US': dict(
        rotulo='Connect IDE', titulo='Confirm the code shown in your IDE',
        pedidoA='Requested 20 seconds ago by', pedidoIde='VS Code on macOS',
        pedidoB='. You never type a password inside the IDE.',
        vaiPoder='The Peer will be able to', pode1='Read the code around events, in the projects where you turn it on',
        pode2='Record evidence in your Code profile',
        nunca='It will never be able to', nunca1='See passwords, payments or Platform data',
        nunca2='Read .env, secrets or files ignored by Git',
        conectar='Connect this IDE', naoFuiEu='It wasn’t me',
        dispositivos='Connected devices', jaConectadas='Already connected',
        cadaIde='Each IDE is a device on your account',
        cursorSub='connected 12 days ago · last used yesterday', desconectar='Disconnect',
    ),
    'es-ES': dict(
        rotulo='Conectar IDE', titulo='Confirma el código que aparece en tu IDE',
        pedidoA='Solicitado hace 20 segundos por', pedidoIde='VS Code en macOS',
        pedidoB='. Nunca se escribe una contraseña dentro del IDE.',
        vaiPoder='El Peer podrá', pode1='Leer el fragmento alrededor de los eventos, en los proyectos donde lo actives',
        pode2='Registrar evidencias en tu perfil de Code',
        nunca='Nunca podrá', nunca1='Ver contraseñas, pagos o datos de Platform',
        nunca2='Leer .env, secrets o archivos ignorados por Git',
        conectar='Conectar este IDE', naoFuiEu='No he sido yo',
        dispositivos='Dispositivos conectados', jaConectadas='Ya conectados',
        cadaIde='Cada IDE es un dispositivo de tu cuenta',
        cursorSub='conectado hace 12 días · último uso ayer', desconectar='Desconectar',
    ),
}

PLANOS = {
    'pt-BR': dict(
        periodo='Período de cobrança', mensal='Mensal', anual='Anual',
        titulo='Planos do Muriki Code',
        sub='A assinatura do Code é separada da do Platform. A conta Muriki é a mesma nos dois, e assinar um não muda nada no outro.',
        ariaStarter='Plano Starter', ariaPro='Plano Pro',
        gratis='Grátis', semCartao='para sempre, sem cartão', preco='R$ 49,90', porMes=' /mês', porAno='ou R$ 499 por ano',
        s1='Trilhas e exercícios com testes', s2='Perfil de competência e sua evolução', s3='Avaliação por competência',
        s4='Limite mensal de exercícios',
        p1='Tudo do Starter', p2='Peer na IDE, no VS Code e no Cursor', p3='Avaliações avançadas, com o porquê de cada nota',
        p4='Até 100 exercícios por mês', p5='Limite mensal de uso do Peer e da conversa',
        aDefinir='a definir', atualBotao='Seu plano atual', atual='atual', recomendado='recomendado', assinar='Assinar o Pro',
        r1='Cancelou? O Pro fica até o fim do período pago. Depois você volta ao Starter sem perder histórico nem perfil.',
        r2='Assinar o Code não dá nada no Platform, e o contrário também não.',
        r3='O Peer e a conversa usam IA, por isso têm limite mensal por pessoa.',
    ),
    'en-US': dict(
        periodo='Billing period', mensal='Monthly', anual='Yearly',
        titulo='Muriki Code plans',
        sub='The Code subscription is separate from Platform’s. Your Muriki account is the same for both, and subscribing to one changes nothing in the other.',
        ariaStarter='Starter plan', ariaPro='Pro plan',
        gratis='Free', semCartao='forever, no card', preco='R$49.90', porMes=' /month', porAno='or R$499 a year',
        s1='Tracks and exercises with tests', s2='Competency profile and its progress', s3='Evaluation per competency',
        s4='Monthly exercise limit',
        p1='Everything in Starter', p2='Peer in your IDE, in VS Code and Cursor', p3='Advanced evaluations, with the why behind each grade',
        p4='Up to 100 exercises a month', p5='Monthly usage limit for the Peer and chat',
        aDefinir='to be defined', atualBotao='Your current plan', atual='current', recomendado='recommended', assinar='Subscribe to Pro',
        r1='Canceled? Pro stays until the end of the paid period. Then you go back to Starter without losing history or profile.',
        r2='Subscribing to Code gives you nothing in Platform, and the other way around.',
        r3='The Peer and chat use AI, so they have a monthly limit per person.',
    ),
    'es-ES': dict(
        periodo='Periodo de facturación', mensal='Mensual', anual='Anual',
        titulo='Planes de Muriki Code',
        sub='La suscripción de Code es independiente de la de Platform. La cuenta Muriki es la misma en los dos, y suscribirte a uno no cambia nada en el otro.',
        ariaStarter='Plan Starter', ariaPro='Plan Pro',
        gratis='Gratis', semCartao='para siempre, sin tarjeta', preco='R$ 49,90', porMes=' /mes', porAno='o R$ 499 al año',
        s1='Rutas y ejercicios con pruebas', s2='Perfil de competencias y su evolución', s3='Evaluación por competencia',
        s4='Límite mensual de ejercicios',
        p1='Todo lo de Starter', p2='Peer en el IDE, en VS Code y Cursor', p3='Evaluaciones avanzadas, con el porqué de cada nota',
        p4='Hasta 100 ejercicios al mes', p5='Límite mensual de uso del Peer y la conversación',
        aDefinir='por definir', atualBotao='Tu plan actual', atual='actual', recomendado='recomendado', assinar='Suscribirme a Pro',
        r1='¿Has cancelado? Pro se mantiene hasta el final del periodo pagado. Después vuelves a Starter sin perder historial ni perfil.',
        r2='Suscribirte a Code no te da nada en Platform, y al revés tampoco.',
        r3='El Peer y la conversación usan IA, por eso tienen un límite mensual por persona.',
    ),
}

JORNADA = {
    'pt-BR': dict(
        rotulo='Primeiro acesso · 1 de 2', titulo='Por onde você quer começar?',
        sub='Escolha o nível que mais parece com o seu momento. É só o ponto de partida: '
            'cada competência se ajusta com o que você faz nos exercícios e no Peer.',
        jornadas='Jornadas', aprofundar='aprofundar',
        j1desc='Você já programa e quer autonomia: testar, depurar e entregar sem alguém do lado.',
        j2desc='Você entrega sozinho. A jornada trabalha as decisões: testes, arquitetura, dados e segurança.',
        j3desc='Você decide bem no código. A jornada leva as decisões para o time: desenho de sistemas, observabilidade e revisão.',
        j4desc='Você lidera um time. A jornada é sobre os limites entre sistemas e como eles evoluem.',
        j5desc='Você desenha sistemas. A jornada é rever decisões com evidência e manter o rigor.',
        j6nome='Ainda não sei',
        j6desc='Faça três exercícios curtos e o Code sugere a jornada pelo que você fizer.',
        painel='O que essa escolha muda', partida='Ponto de partida',
        partidaA='Todas as competências começam em', partidaB='. No próximo passo você ajusta o que for diferente.',
        partidaNaoSei='Nenhum nível antes dos três exercícios. Depois, cada competência começa onde eles mostrarem.',
        semNivel='sem nível ainda', foco='Onde a trilha começa', primeiroEx='Primeiro exercício',
        ex1='Validar o formulário de cadastro', ex2='Converter duração em texto para minutos',
        ex3='Revisar um PR que muda o schema de pedidos', ex4='Onde fica o limite de pagamentos no monólito?',
        ex5='Rever uma decisão de arquitetura de dois anos atrás', ex6='Três exercícios curtos, um de cada competência',
        peerTit='Como o Peer começa',
        peer1='Pergunta antes de você rodar os testes e explica quando você travar.',
        peer2='Pergunta pelas decisões e só dá dica quando você pede.',
        peer3='Fica quieto no código e questiona o desenho.',
        peer4='Intervém pouco. Quando fala, é sobre trade-offs entre sistemas.',
        peer5='Só aparece quando você chama.',
        peer6='Só observa até a jornada ser escolhida.',
        comecar='Continuar', comecarTres='Começar os três exercícios',
        trocarDepois='Dá para trocar de jornada quando quiser, sem perder o que já fez.',
    ),
    'en-US': dict(
        rotulo='Getting started · 1 of 2', titulo='Where do you want to start?',
        sub='Pick the level that feels closest to where you are now. It’s just the starting point: '
            'each competency adjusts to what you do in exercises and with the Peer.',
        jornadas='Journeys', aprofundar='go deeper',
        j1desc='You already code and want autonomy: testing, debugging and shipping without someone beside you.',
        j2desc='You ship on your own. The journey works on your decisions: tests, architecture, data and security.',
        j3desc='You make good calls in code. The journey takes them to the team: system design, observability and review.',
        j4desc='You lead a team. The journey is about the boundaries between systems and how they evolve.',
        j5desc='You design systems. The journey is about revisiting decisions with evidence and staying rigorous.',
        j6nome='Not sure yet',
        j6desc='Do three short exercises and Code suggests a journey based on what you do.',
        painel='What this choice changes', partida='Starting point',
        partidaA='Every competency starts at', partidaB='. In the next step you adjust what’s different.',
        partidaNaoSei='No level before the three exercises. After that, each competency starts where they show.',
        semNivel='no level yet', foco='Where the track starts', primeiroEx='First exercise',
        ex1='Validate the sign-up form', ex2='Convert a text duration into minutes',
        ex3='Review a PR that changes the orders schema', ex4='Where does the payments boundary sit in the monolith?',
        ex5='Revisit an architecture decision from two years ago', ex6='Three short exercises, one per competency',
        peerTit='How the Peer starts',
        peer1='Asks before you run the tests and explains when you get stuck.',
        peer2='Asks about your decisions and only gives hints when you ask.',
        peer3='Stays quiet in the code and questions the design.',
        peer4='Rarely steps in. When it does, it’s about trade-offs between systems.',
        peer5='Only shows up when you call it.',
        peer6='Only watches until a journey is chosen.',
        comecar='Continue', comecarTres='Start the three exercises',
        trocarDepois='You can switch journeys any time without losing what you’ve done.',
    ),
    'es-ES': dict(
        rotulo='Primeros pasos · 1 de 2', titulo='¿Por dónde quieres empezar?',
        sub='Elige el nivel que más se parece a tu momento. Es solo el punto de partida: '
            'cada competencia se ajusta con lo que haces en los ejercicios y con el Peer.',
        jornadas='Trayectorias', aprofundar='profundizar',
        j1desc='Ya programas y quieres autonomía: probar, depurar y entregar sin alguien al lado.',
        j2desc='Entregas por tu cuenta. La trayectoria trabaja las decisiones: pruebas, arquitectura, datos y seguridad.',
        j3desc='Decides bien en el código. La trayectoria lleva las decisiones al equipo: diseño de sistemas, observabilidad y revisión.',
        j4desc='Lideras un equipo. La trayectoria trata de los límites entre sistemas y de cómo evolucionan.',
        j5desc='Diseñas sistemas. La trayectoria consiste en revisar decisiones con evidencias y mantener el rigor.',
        j6nome='Aún no lo sé',
        j6desc='Haz tres ejercicios cortos y Code te sugiere una trayectoria según lo que hagas.',
        painel='Qué cambia con esta elección', partida='Punto de partida',
        partidaA='Todas las competencias empiezan en', partidaB='. En el siguiente paso ajustas lo que sea diferente.',
        partidaNaoSei='Ningún nivel antes de los tres ejercicios. Después, cada competencia empieza donde ellos indiquen.',
        semNivel='sin nivel aún', foco='Dónde empieza la ruta', primeiroEx='Primer ejercicio',
        ex1='Validar el formulario de registro', ex2='Convertir una duración en texto a minutos',
        ex3='Revisar un PR que cambia el schema de pedidos', ex4='¿Dónde está el límite de pagos en el monolito?',
        ex5='Revisar una decisión de arquitectura de hace dos años', ex6='Tres ejercicios cortos, uno por competencia',
        peerTit='Cómo empieza el Peer',
        peer1='Pregunta antes de que ejecutes las pruebas y explica cuando te atascas.',
        peer2='Pregunta por las decisiones y solo da pistas cuando las pides.',
        peer3='Se queda callado en el código y cuestiona el diseño.',
        peer4='Interviene poco. Cuando habla, es sobre trade-offs entre sistemas.',
        peer5='Solo aparece cuando lo llamas.',
        peer6='Solo observa hasta que se elige la trayectoria.',
        comecar='Continuar', comecarTres='Empezar los tres ejercicios',
        trocarDepois='Puedes cambiar de trayectoria cuando quieras, sin perder lo que ya has hecho.',
    ),
}


ACESSO = {
    'pt-BR': dict(
        acesso='Acesso', pitch1='Código você já escreve.', pitch2='Aqui você aprende a decidir',
        pitchTxt='Exercícios com testes, um Peer que pergunta em vez de responder e um perfil que mostra onde '
                 'você está de verdade. Sem autocompletar: quem pensa é você.',
        direitos='© 2026 Muriki — todos os direitos',
        entrarCom='Entrar com', ou='ou email', emailLabel='Email', emailPh='voce@email.com',
        senhaLabel='Senha', senhaPh='Sua senha', esqueci='Esqueci a senha',
        mostrarSenha='Mostrar senha', ocultarSenha='Esconder senha', lembrar='Lembrar de mim',
        entrar='Entrar', heroA='Que bom', heroB='te ver de novo.',
        subEntrar='Use sua conta Muriki, a mesma do Platform. Não tem?', criarLink='Crie uma aqui',
        rotuloCriar='Criar conta', heroCriarA='Comece pela', heroCriarB='sua jornada.',
        subCriar='Uma conta Muriki serve para o Code e para o Platform. Já tem?', entrarLink='Entre aqui',
        criarCom='Criar com', nomeLabel='Nome', nomePh='Seu nome', senhaNovaPh='Mínimo de 8 caracteres',
        forcaAria='Força da senha', reqAria='Requisitos da senha',
        forcaFraca='Fraca', forcaMedia='Média', forcaForte='Forte', forcaMuitoForte='Muito forte',
        req8='8 caracteres', reqNum='1 número', reqMin='1 minúscula', reqMai='1 maiúscula',
        termosA='Li e aceito os', termos='termos de uso', termosE='e a', privacidade='política de privacidade',
        semTreino='Seu código não é usado para treinar modelos de IA.', criarBotao='Criar conta',
    ),
    'en-US': dict(
        acesso='Access', pitch1='You already write code.', pitch2='Here you learn to decide',
        pitchTxt='Exercises with tests, a Peer that asks instead of answering, and a profile that shows where '
                 'you really stand. No autocomplete: you do the thinking.',
        direitos='© 2026 Muriki — all rights reserved',
        entrarCom='Sign in with', ou='or email', emailLabel='Email', emailPh='you@email.com',
        senhaLabel='Password', senhaPh='Your password', esqueci='Forgot password',
        mostrarSenha='Show password', ocultarSenha='Hide password', lembrar='Remember me',
        entrar='Sign in', heroA='Good to see', heroB='you again.',
        subEntrar='Use your Muriki account, the same as Platform. Don’t have one?', criarLink='Create one here',
        rotuloCriar='Create account', heroCriarA='Start with', heroCriarB='your journey.',
        subCriar='One Muriki account works for Code and Platform. Already have one?', entrarLink='Sign in here',
        criarCom='Sign up with', nomeLabel='Name', nomePh='Your name', senhaNovaPh='At least 8 characters',
        forcaAria='Password strength', reqAria='Password requirements',
        forcaFraca='Weak', forcaMedia='Medium', forcaForte='Strong', forcaMuitoForte='Very strong',
        req8='8 characters', reqNum='1 number', reqMin='1 lowercase', reqMai='1 uppercase',
        termosA='I have read and accept the', termos='terms of use', termosE='and the', privacidade='privacy policy',
        semTreino='Your code is never used to train AI models.', criarBotao='Create account',
    ),
    'es-ES': dict(
        acesso='Acceso', pitch1='Código ya escribes.', pitch2='Aquí aprendes a decidir',
        pitchTxt='Ejercicios con pruebas, un Peer que pregunta en lugar de responder y un perfil que muestra dónde '
                 'estás de verdad. Sin autocompletar: quien piensa eres tú.',
        direitos='© 2026 Muriki — todos los derechos',
        entrarCom='Entrar con', ou='o email', emailLabel='Email', emailPh='tu@email.com',
        senhaLabel='Contraseña', senhaPh='Tu contraseña', esqueci='He olvidado la contraseña',
        mostrarSenha='Mostrar contraseña', ocultarSenha='Ocultar contraseña', lembrar='Recordarme',
        entrar='Entrar', heroA='Qué bueno', heroB='verte de nuevo.',
        subEntrar='Usa tu cuenta Muriki, la misma de Platform. ¿No tienes una?', criarLink='Créala aquí',
        rotuloCriar='Crear cuenta', heroCriarA='Empieza por', heroCriarB='tu trayectoria.',
        subCriar='Una cuenta Muriki sirve para Code y para Platform. ¿Ya tienes una?', entrarLink='Entra aquí',
        criarCom='Crear con', nomeLabel='Nombre', nomePh='Tu nombre', senhaNovaPh='Mínimo 8 caracteres',
        forcaAria='Seguridad de la contraseña', reqAria='Requisitos de la contraseña',
        forcaFraca='Débil', forcaMedia='Media', forcaForte='Fuerte', forcaMuitoForte='Muy fuerte',
        req8='8 caracteres', reqNum='1 número', reqMin='1 minúscula', reqMai='1 mayúscula',
        termosA='He leído y acepto los', termos='términos de uso', termosE='y la', privacidade='política de privacidad',
        semTreino='Tu código nunca se usa para entrenar modelos de IA.', criarBotao='Crear cuenta',
    ),
}

PRIMEIRO = {
    'pt-BR': dict(
        primeiroChip='primeiro exercício', naoRodou='não rodou', rodeCom='Rode com ⌘ ↵ para ver o resultado',
        dicasDisp='3 dicas disponíveis', pedirDica='Pedir dica', guiaAria='Guia do primeiro exercício', de3='de 3',
        g1t='Aqui quem escreve é você',
        g1d='O editor não autocompleta nem sugere. Crie os arquivos que precisar na árvore ao lado; o que veio do exercício tem cadeado.',
        g2t='Os testes dizem se funcionou',
        g2d='Rode com ⌘ ↵. Cada falha mostra o esperado e o recebido, bem aqui do lado do código.',
        g3t='Explique com as suas palavras',
        g3d='A explicação vai para a avaliação junto com o código. É ela que mostra que você entendeu, não só que passou.',
        pular='Pular', proximo='Próximo', comecarGuia='Começar',
    ),
    'en-US': dict(
        primeiroChip='first exercise', naoRodou='not run yet', rodeCom='Run with ⌘ ↵ to see the result',
        dicasDisp='3 hints available', pedirDica='Ask for a hint', guiaAria='First exercise guide', de3='of 3',
        g1t='Here, you write the code',
        g1d='The editor doesn’t autocomplete or suggest. Create the files you need in the tree beside it; what came with the exercise has a lock.',
        g2t='The tests tell you if it works',
        g2d='Run them with ⌘ ↵. Each failure shows what was expected and what came back, right next to the code.',
        g3t='Explain it in your own words',
        g3d='Your explanation goes into the evaluation with the code. It shows you understood, not just that it passed.',
        pular='Skip', proximo='Next', comecarGuia='Start',
    ),
    'es-ES': dict(
        primeiroChip='primer ejercicio', naoRodou='sin ejecutar', rodeCom='Ejecuta con ⌘ ↵ para ver el resultado',
        dicasDisp='3 pistas disponibles', pedirDica='Pedir una pista', guiaAria='Guía del primer ejercicio', de3='de 3',
        g1t='Aquí escribes tú',
        g1d='El editor no autocompleta ni sugiere. Crea los archivos que necesites en el árbol de al lado; lo que viene del ejercicio tiene candado.',
        g2t='Las pruebas dicen si funciona',
        g2d='Ejecútalas con ⌘ ↵. Cada fallo muestra lo esperado y lo recibido, justo al lado del código.',
        g3t='Explícalo con tus palabras',
        g3d='La explicación va a la evaluación junto con el código. Es la que muestra que lo has entendido, no solo que ha pasado.',
        pular='Saltar', proximo='Siguiente', comecarGuia='Empezar',
    ),
}

PERFIL_VAZIO = {
    'pt-BR': dict(
        subVazio='Ainda sem evidência. O ponto de partida é o que você declarou no primeiro acesso, '
                 'e cada exercício enviado confirma ou ajusta uma competência.',
        trocarJornada='Trocar de jornada', entraPrimeiro='entra no 1º exercício',
        primeiroTitulo='Converter duração em texto para minutos',
        primeiroTxt='Seu primeiro exercício: tem testes, dicas sob pedido e uma pergunta para você explicar a solução.',
        nadaAinda='Nada ainda. Cada solução, explicação e conversa com o Peer aparece aqui, com a fonte e o peso.',
        trajVazio='A trajetória compara você com você mesmo: a primeira solução enviada vira o ponto de comparação das próximas.',
    ),
    'en-US': dict(
        subVazio='No evidence yet. The starting point is what you declared at first access, '
                 'and each exercise you submit confirms or adjusts a competency.',
        trocarJornada='Switch journey', entraPrimeiro='in your first exercise',
        primeiroTitulo='Convert a text duration into minutes',
        primeiroTxt='Your first exercise: it has tests, hints on request and a question for you to explain your solution.',
        nadaAinda='Nothing yet. Every solution, explanation and conversation with the Peer shows up here, with its source and weight.',
        trajVazio='The trajectory compares you with yourself: your first submitted solution becomes the baseline for the next ones.',
    ),
    'es-ES': dict(
        subVazio='Aún sin evidencias. El punto de partida es lo que declaraste en el primer acceso, '
                 'y cada ejercicio enviado confirma o ajusta una competencia.',
        trocarJornada='Cambiar de trayectoria', entraPrimeiro='entra en el 1.er ejercicio',
        primeiroTitulo='Convertir una duración en texto a minutos',
        primeiroTxt='Tu primer ejercicio: tiene pruebas, pistas a demanda y una pregunta para que expliques tu solución.',
        nadaAinda='Nada todavía. Cada solución, explicación y conversación con el Peer aparece aquí, con su fuente y su peso.',
        trajVazio='La trayectoria te compara contigo: la primera solución enviada es el punto de comparación de las siguientes.',
    ),
}

COMPETENCIA = {
    'pt-BR': dict(
        declaradoSuf='declarado', confirmadoSuf='confirmado', aConfirmarSuf='a confirmar',
        confirmadoPor='confirmado por 12 evidências', editarDecl='Editar declarado',
        caminhoTit='Caminho para confirmar',
        caminhoTxt='3 exercícios de nível Senior com rubrica de 4 de 5 ou mais confirmam. '
                   'O Learning escolhe os que cobrem o que falta nas suas soluções.',
        zeroDeTres='0 de 3', exA='Slots com relógio injetado', exB='Cache com expiração testável',
        exC='Retentativas com tempo simulado', proximo='próximo', comecar='Começar',
        agendaNota='ficou em 3 de 5 e não contou: a rubrica de Senior pede 4 de 5.',
        historicoTit='Histórico do nível',
        d1='12 set', h1d='O declarado ficou acima do observado. Três exercícios de Senior confirmam.',
        h2d='Você mudou o declarado no perfil.',
        d3='5 set', h3d='3 submissões de nível Pleno com rubrica alta:',
        d4='20 ago', h4d='No primeiro acesso, pela jornada.',
        fontesTit='Evidências por fonte', fonteExercicio='Exercício', fonteExplicacao='Explicação',
        fontePeer='Peer na IDE', fontePlayground='Playground', pesoForte='forte', pesoLeve='leve', total='Total',
        fontesNota='Evidência leve ajusta a confiança e orienta o Peer. Sozinha, não muda o nível.',
        trajTit='Trajetória', trajSub='A mesma competência, com três meses de diferença.',
        junho='junho', hoje='hoje', trajMetric='Asserts por teste', trajAntes='1,4', trajDepois='2,6',
    ),
    'en-US': dict(
        declaradoSuf='declared', confirmadoSuf='confirmed', aConfirmarSuf='to confirm',
        confirmadoPor='confirmed by 12 pieces of evidence', editarDecl='Edit declared level',
        caminhoTit='Path to confirm',
        caminhoTxt='3 Senior-level exercises with a rubric of 4 of 5 or more would confirm it. '
                   'Learning picks the ones that cover what your solutions are missing.',
        zeroDeTres='0 of 3', exA='Slots with an injected clock', exB='Cache with testable expiry',
        exC='Retries with simulated time', proximo='next', comecar='Start',
        agendaNota='scored 3 of 5 and didn’t count: the Senior rubric asks for 4 of 5.',
        historicoTit='Level history',
        d1='Sep 12', h1d='Declared moved above observed. Three Senior exercises would confirm it.',
        h2d='You changed the declared level in your profile.',
        d3='Sep 5', h3d='3 Mid-level submissions with a high rubric score:',
        d4='Aug 20', h4d='At first access, from your journey.',
        fontesTit='Evidence by source', fonteExercicio='Exercise', fonteExplicacao='Explanation',
        fontePeer='Peer in your IDE', fontePlayground='Playground', pesoForte='strong', pesoLeve='light', total='Total',
        fontesNota='Light evidence adjusts confidence and guides the Peer. On its own, it never changes a level.',
        trajTit='Trajectory', trajSub='The same competency, three months apart.',
        junho='June', hoje='today', trajMetric='Asserts per test', trajAntes='1.4', trajDepois='2.6',
    ),
    'es-ES': dict(
        declaradoSuf='declarado', confirmadoSuf='confirmado', aConfirmarSuf='por confirmar',
        confirmadoPor='confirmado por 12 evidencias', editarDecl='Editar el declarado',
        caminhoTit='Camino para confirmar',
        caminhoTxt='3 ejercicios de nivel Senior con una rúbrica de 4 de 5 o más lo confirman. '
                   'Learning elige los que cubren lo que falta en tus soluciones.',
        zeroDeTres='0 de 3', exA='Slots con reloj inyectado', exB='Caché con caducidad comprobable',
        exC='Reintentos con tiempo simulado', proximo='siguiente', comecar='Empezar',
        agendaNota='se quedó en 3 de 5 y no contó: la rúbrica de Senior pide 4 de 5.',
        historicoTit='Historial del nivel',
        d1='12 sept', h1d='El declarado quedó por encima del observado. Tres ejercicios de Senior lo confirman.',
        h2d='Has cambiado el declarado en tu perfil.',
        d3='5 sept', h3d='3 envíos de nivel Intermedio con una rúbrica alta:',
        d4='20 ago', h4d='En el primer acceso, desde la trayectoria.',
        fontesTit='Evidencias por fuente', fonteExercicio='Ejercicio', fonteExplicacao='Explicación',
        fontePeer='Peer en el IDE', fontePlayground='Playground', pesoForte='fuerte', pesoLeve='ligera', total='Total',
        fontesNota='La evidencia ligera ajusta la confianza y orienta al Peer. Por sí sola, no cambia el nivel.',
        trajTit='Trayectoria', trajSub='La misma competencia, con tres meses de diferencia.',
        junho='junio', hoje='hoy', trajMetric='Asserts por prueba', trajAntes='1,4', trajDepois='2,6',
    ),
}

AJUSTE = {
    'pt-BR': dict(
        rotulo='Primeiro acesso · 2 de 2', titulo='Onde você é diferente?',
        sub='A jornada marcou tudo como Pleno. Ajuste o que não for verdade e diga quais linguagens você usa. '
            'É só o ponto de partida: as evidências confirmam ou ajustam depois.',
        grupoLing='Linguagens', grupoEng='Engenharia', naoUso='Não uso', ajustado='ajustado',
        ajuste1='ajuste', ajustes='ajustes', semAjuste='nenhum ajuste', niveisAria='Nível declarado em',
        voltar='Voltar à jornada', continuar='Começar o primeiro exercício',
        mudarDepois='Dá para mudar o declarado depois, no perfil.',
    ),
    'en-US': dict(
        rotulo='Getting started · 2 of 2', titulo='Where are you different?',
        sub='Your journey set everything to Mid-level. Change what isn’t true and tell us which languages you use. '
            'It’s only the starting point: evidence confirms or adjusts it later.',
        grupoLing='Languages', grupoEng='Engineering', naoUso='Don’t use', ajustado='adjusted',
        ajuste1='adjustment', ajustes='adjustments', semAjuste='no adjustments', niveisAria='Declared level in',
        voltar='Back to journeys', continuar='Start the first exercise',
        mudarDepois='You can change it later in your profile.',
    ),
    'es-ES': dict(
        rotulo='Primeros pasos · 2 de 2', titulo='¿Dónde eres diferente?',
        sub='La trayectoria marcó todo como Intermedio. Ajusta lo que no sea verdad y dinos qué lenguajes usas. '
            'Es solo el punto de partida: las evidencias lo confirman o lo ajustan después.',
        grupoLing='Lenguajes', grupoEng='Ingeniería', naoUso='No lo uso', ajustado='ajustado',
        ajuste1='ajuste', ajustes='ajustes', semAjuste='ningún ajuste', niveisAria='Nivel declarado en',
        voltar='Volver a las trayectorias', continuar='Empezar el primer ejercicio',
        mudarDepois='Puedes cambiarlo después, en tu perfil.',
    ),
}

PLAYGROUND = {
    'pt-BR': dict(
        titulo='Playground', sub='Código livre, sem enunciado nem nota. O Peer acompanha usando o seu perfil como contexto.',
        nota='O que você faz aqui vira evidência leve de processo: ajuda o Peer, mas sozinho não muda nível.',
        linguagemAria='Linguagem', rodar='Rodar', novoArquivo='Novo arquivo', saida='Saída', rodouAgora='rodou agora · 0,3 s',
        observando='observando', contexto='usa o seu perfil',
        pergunta='Uma linha do horas.csv tem os minutos vazios. O que a função deveria fazer com ela: '
                 'pular, contar como zero ou parar com erro?',
        registrada='registrada como evidência leve de', perguntePeer='Pergunte ao Peer',
        placeholderPeer='Escreva o que você está pensando', enviaAtalho='⌘ ↵ envia', enviarAria='Enviar ao Peer',
        editorAria='Editor', abertos='Arquivos abertos', atalho='⌘ ↵ roda', semAuto='sem autocompletar: aqui quem escreve é você',
    ),
    'en-US': dict(
        titulo='Playground', sub='Free code, no problem statement and no grade. The Peer follows along, using your profile as context.',
        nota='What you do here becomes light process evidence: it helps the Peer, but never changes a level on its own.',
        linguagemAria='Language', rodar='Run', novoArquivo='New file', saida='Output', rodouAgora='ran just now · 0.3 s',
        observando='watching', contexto='uses your profile',
        pergunta='One row in horas.csv has empty minutes. What should the function do with it: '
                 'skip it, count it as zero or stop with an error?',
        registrada='registered as light evidence for', perguntePeer='Ask the Peer',
        placeholderPeer='Write what you’re thinking', enviaAtalho='⌘ ↵ sends', enviarAria='Send to the Peer',
        editorAria='Editor', abertos='Open files', atalho='⌘ ↵ runs', semAuto='no autocomplete: here, you write the code',
    ),
    'es-ES': dict(
        titulo='Playground', sub='Código libre, sin enunciado ni nota. El Peer te acompaña usando tu perfil como contexto.',
        nota='Lo que haces aquí se convierte en evidencia ligera de proceso: ayuda al Peer, pero por sí sola no cambia ningún nivel.',
        linguagemAria='Lenguaje', rodar='Ejecutar', novoArquivo='Nuevo archivo', saida='Salida', rodouAgora='ejecutado ahora · 0,3 s',
        observando='observando', contexto='usa tu perfil',
        pergunta='Una fila de horas.csv tiene los minutos vacíos. ¿Qué debería hacer la función con ella: '
                 'saltarla, contarla como cero o parar con un error?',
        registrada='registrada como evidencia ligera de', perguntePeer='Pregunta al Peer',
        placeholderPeer='Escribe lo que estás pensando', enviaAtalho='⌘ ↵ envía', enviarAria='Enviar al Peer',
        editorAria='Editor', abertos='Archivos abiertos', atalho='⌘ ↵ ejecuta', semAuto='sin autocompletar: aquí escribes tú',
    ),
}

def juntar(*partes):
    textos = {}
    for idioma in IDIOMAS:
        d = {}
        for p in partes:
            repetidas = set(d) & set(p[idioma])
            assert not repetidas, f'chave repetida: {repetidas}'
            d.update(p[idioma])
        textos[idioma] = d
    assert all(set(v) == set(textos['pt-BR']) for v in textos.values()), 'chaves diferentes entre idiomas'
    return textos
