# Textos do Playground com tipos e do desenho livre (2026-10-04), nos três idiomas da web.
# Contrato: swell-docs/muriki-api/features/arch-cloud/fd-desenho.md. Títulos de desenho e notas são
# da pessoa, então ficam fora daqui (como as etapas das trilhas).

TEXTOS = {
    'pt-BR': dict(
        pgPonto1='AWS, GCP e Azure, ou genérico', pgPonto2='Grupos de rede e notas soltas', pgPonto3='Simule e veja onde ele quebra',
        pgPonto4='JavaScript e Python', pgPonto5='O Peer junto, sem nota nem nível', pgAvisamos='Avisamos quando chegar.',
        pgCriado1='criado em 2 de out.', pgCriado2='criado em 26 de set.', pgCriado3='criado em 15 de set.',
        pgTitulo='Playground', pgSub='Crie fora dos exercícios. Nada aqui vira nota nem muda o seu nível.',
        pgDesenho='Desenho de arquitetura', pgDesenhoTxt='Desenhe livre, com provedores, grupos e notas, e simule onde ele quebra.',
        pgNovo='Novo desenho', pgCodigo='Código livre', pgCodigoTxt='Escreva e rode código fora de um exercício, com o Peer junto.',
        pgEmBreve='em breve', pgSeus='Seus desenhos',
        pgSalvo2h='salvo há 2 h', pgSalvoOntem='salvo ontem', pgSalvo4d='salvo há 4 dias', pgApagar='Apagar',
        pgLimiteTitulo='O Starter guarda até 3 desenhos', pgLimiteTxt='Para criar outro, apague um dos seus desenhos ou assine o Pro.', pgLimitePro='No Pro, desenhe sem limite.',
        plAgoraNao='Agora não', plConhecerPro='Conhecer o Pro', plEntendi='Entendi',
        dlVoltar='Playground', dlSalvo='Salvo',
        pecasTit='Peças', gruposTit='Grupos', notasTit='Notas', notasConta='2 de 20', nota='Nota',
        notasDica='Texto solto no desenho. Não liga a nada e não conta nas regras.',
        provedor='Provedor', generico='Genérico', aws='AWS', gcp='GCP', azure='Azure', provedorDica='Cada peça ganha o primeiro serviço do tipo. Troque na peça selecionada.',
        dlDica='Clique numa peça à esquerda para pôr no diagrama, e arraste de uma alça para ligar.',
        simular='Simular', status='6 peças · 5 ligações · 3 grupos · 2 notas', pDecisao='Decisão', nDecisao='Estoque disponível?', nAvisar='Avisar cliente', sim='sim', nao='não',
        pCliente='Cliente', pApi='API', pBanco='Banco de dados', pCache='Cache', pFila='Fila', pBalanceador='Balanceador',
        gRegiao='Região', gZona='Zona', gVpc='VPC', gPublica='Sub-rede pública', gPrivada='Sub-rede privada',
        chama='chama', le='lê', escreve='escreve', nApp='App', nEntrada='Entrada', nPedidos='Pedidos', nEstoque='Estoque',
        nota1='Pico às 19 h: 3x o normal.', nota2='Réplica de leitura\ndepois do lançamento',
    ),
    'en-US': dict(
        pgPonto1='AWS, GCP and Azure, or generic', pgPonto2='Network groups and loose notes', pgPonto3='Simulate and see where it breaks',
        pgPonto4='JavaScript and Python', pgPonto5='Peer along, no grade or level', pgAvisamos='We will let you know when it arrives.',
        pgCriado1='created Oct 2', pgCriado2='created Sep 26', pgCriado3='created Sep 15',
        pgTitulo='Playground', pgSub='Create outside the exercises. Nothing here becomes a grade or changes your level.',
        pgDesenho='Architecture drawing', pgDesenhoTxt='Draw freely, with providers, groups and notes, and simulate where it breaks.',
        pgNovo='New drawing', pgCodigo='Free code', pgCodigoTxt='Write and run code outside an exercise, with Peer along.',
        pgEmBreve='soon', pgSeus='Your drawings',
        pgSalvo2h='saved 2 hr ago', pgSalvoOntem='saved yesterday', pgSalvo4d='saved 4 days ago', pgApagar='Delete',
        pgLimiteTitulo='Starter keeps up to 3 drawings', pgLimiteTxt='To create another, delete one of your drawings or subscribe to Pro.', pgLimitePro='On Pro, draw without limits.',
        plAgoraNao='Not now', plConhecerPro='See Pro', plEntendi='Got it',
        dlVoltar='Playground', dlSalvo='Saved',
        pecasTit='Pieces', gruposTit='Groups', notasTit='Notes', notasConta='2 of 20', nota='Note',
        notasDica='Loose text on the drawing. It connects to nothing and does not count in rules.',
        provedor='Provider', generico='Generic', aws='AWS', gcp='GCP', azure='Azure', provedorDica='Each piece gets the first service of its type. Change it on the selected piece.',
        dlDica='Click a piece on the left to add it, and drag from a handle to connect.',
        simular='Simulate', status='6 pieces · 5 connections · 3 groups · 2 notes', pDecisao='Decision', nDecisao='In stock?', nAvisar='Notify customer', sim='yes', nao='no',
        pCliente='Client', pApi='API', pBanco='Database', pCache='Cache', pFila='Queue', pBalanceador='Load balancer',
        gRegiao='Region', gZona='Zone', gVpc='VPC', gPublica='Public subnet', gPrivada='Private subnet',
        chama='calls', le='reads', escreve='writes', nApp='App', nEntrada='Entry', nPedidos='Orders', nEstoque='Stock',
        nota1='Peak at 7 pm: 3x normal.', nota2='Read replica\nafter launch',
    ),
    'es-ES': dict(
        pgPonto1='AWS, GCP y Azure, o genérico', pgPonto2='Grupos de red y notas sueltas', pgPonto3='Simula y ve dónde se rompe',
        pgPonto4='JavaScript y Python', pgPonto5='El Peer al lado, sin nota ni nivel', pgAvisamos='Te avisamos cuando llegue.',
        pgCriado1='creado el 2 de oct.', pgCriado2='creado el 26 de sept.', pgCriado3='creado el 15 de sept.',
        pgTitulo='Playground', pgSub='Crea fuera de los ejercicios. Nada aquí se vuelve nota ni cambia tu nivel.',
        pgDesenho='Diseño de arquitectura', pgDesenhoTxt='Diseña libre, con proveedores, grupos y notas, y simula dónde se rompe.',
        pgNovo='Nuevo diseño', pgCodigo='Código libre', pgCodigoTxt='Escribe y ejecuta código fuera de un ejercicio, con el Peer al lado.',
        pgEmBreve='pronto', pgSeus='Tus diseños',
        pgSalvo2h='guardado hace 2 h', pgSalvoOntem='guardado ayer', pgSalvo4d='guardado hace 4 días', pgApagar='Borrar',
        pgLimiteTitulo='El Starter guarda hasta 3 diseños', pgLimiteTxt='Para crear otro, borra uno de tus diseños o suscríbete a Pro.', pgLimitePro='En Pro, diseña sin límite.',
        plAgoraNao='Ahora no', plConhecerPro='Conocer Pro', plEntendi='Entendido',
        dlVoltar='Playground', dlSalvo='Guardado',
        pecasTit='Piezas', gruposTit='Grupos', notasTit='Notas', notasConta='2 de 20', nota='Nota',
        notasDica='Texto suelto en el diseño. No se conecta a nada y no cuenta en las reglas.',
        provedor='Proveedor', generico='Genérico', aws='AWS', gcp='GCP', azure='Azure', provedorDica='Cada pieza recibe el primer servicio del tipo. Cámbialo en la pieza seleccionada.',
        dlDica='Haz clic en una pieza a la izquierda para agregarla, y arrastra desde un punto para conectar.',
        simular='Simular', status='6 piezas · 5 conexiones · 3 grupos · 2 notas', pDecisao='Decisión', nDecisao='¿Hay stock?', nAvisar='Avisar al cliente', sim='sí', nao='no',
        pCliente='Cliente', pApi='API', pBanco='Base de datos', pCache='Caché', pFila='Cola', pBalanceador='Balanceador',
        gRegiao='Región', gZona='Zona', gVpc='VPC', gPublica='Subred pública', gPrivada='Subred privada',
        chama='llama', le='lee', escreve='escribe', nApp='App', nEntrada='Entrada', nPedidos='Pedidos', nEstoque='Stock',
        nota1='Pico a las 19 h: 3x lo normal.', nota2='Réplica de lectura\ndespués del lanzamiento',
    ),
}
