# Textos da Evolução (2026-10-01), no contrato aprovado da API (swell-docs/muriki-api/features/code-evolution),
# nos três idiomas. Os nomes das competências, das trilhas, das etapas e dos exercícios vêm da API como o
# conteúdo escreve (pt), então ficam fora daqui.

TEXTOS = {
    'pt-BR': dict(
        evTitulo='Evolução',
        evSub='Sempre contra o seu próprio histórico. O nível só sobe, e nada aqui compara você com outra pessoa.',
        comoMedido='Como o nível é medido',
        competencias='Suas competências', grupoJs='JavaScript', grupoArq='Arquitetura',
        colComp='Competência', colNivel='Nível', colConfirmado='Confirmado', colDeclarado='Declarado', colProximo='Próximo nível',
        confirmadoSuf='confirmado', declaradoSuf='declarado', naoConfirmado='ainda não confirmado',
        falta='falta', faltam='faltam', etapa='etapa', etapas='etapas', semEtapas='sem etapas ainda',
        noTopo='no último nível',
        nasTrilhas='Nas trilhas', feitas='feitas', puladas='puladas pelo exercício de entrada',
        cobertas='cobertas pelo seu nível', pendentes='pendentes',
        noTempo='Evolução no tempo',
        noTempoSub='O nível confirmado de cada competência, semana a semana. A linha começa no seu ponto de partida e só sobe.',
        legPartida='ponto de partida', legConfirmacao='confirmação',
        jul='jul', ago='ago', set='set',
        trajetoria='Trajetória',
        trajetoriaSub='A mesma etapa, a primeira aprovação ao lado da mais recente. Sem nota nem comparação: só o seu caminho.',
        primeira='Primeira aprovação', recente='Mais recente',
        mTentativas='Tentativas até passar', mDicas='Dicas reveladas', mExplicacao='Explicação',
        mTempo='Tempo até passar', mPeer='Conversas com o Peer', de2='de 2', minutos='min',
        dJul2='2 jul', dSet18='18 set',
        nivelFund='Fundamentos', nivelJunior='Junior', nivelPleno='Pleno', nivelSenior='Senior',
        voltarEvolucao='Evolução',
        caminhoTit='Caminho na trilha', caminhoSub='As etapas desta competência nas suas trilhas, nível por nível.',
        estFeita='feita', estPulada='pulada pelo exercício de entrada', estCoberta='coberta pelo seu nível',
        seniorSem='Senior ainda não tem etapas nas trilhas. Quando tiver, elas aparecem aqui.',
        historicoTit='Histórico do nível',
        hPlenoConf='Pleno confirmado', hPlenoConfTxt='Três soluções de nível Pleno com a explicação mostrando o porquê.',
        hPartida='Ponto de partida: Junior', hPartidaTxt='O primeiro nível confirmado. Daqui para frente, a linha só sobe.',
        dAgo='14 ago',
        vazioSub='Ainda sem exercício enviado. Cada competência mostra o nível que você declarou no primeiro acesso, até um exercício confirmar.',
        vazioTempoTit='No tempo e trajetória',
        vazioTempoTxt='O histórico começa no seu primeiro nível confirmado. Depois disso, aqui aparecem o nível semana a semana e a sua primeira aprovação, que vira o ponto de comparação das próximas.',
        comecarPrimeiro='Começar o primeiro exercício',
    ),
    'en-US': dict(
        evTitulo='Progress',
        evSub='Always against your own history. Your level only goes up, and nothing here compares you with anyone else.',
        comoMedido='How the level is measured',
        competencias='Your competencies', grupoJs='JavaScript', grupoArq='Architecture',
        colComp='Competency', colNivel='Level', colConfirmado='Confirmed', colDeclarado='Declared', colProximo='Next level',
        confirmadoSuf='confirmed', declaradoSuf='declared', naoConfirmado='not confirmed yet',
        falta='missing', faltam='missing', etapa='step', etapas='steps', semEtapas='no steps yet',
        noTopo='at the top level',
        nasTrilhas='In the tracks', feitas='done', puladas='skipped by the entry exercise',
        cobertas='covered by your level', pendentes='to do',
        noTempo='Over time',
        noTempoSub='Each competency’s confirmed level, week by week. The line starts at your starting point and only goes up.',
        legPartida='starting point', legConfirmacao='confirmation',
        jul='Jul', ago='Aug', set='Sep',
        trajetoria='Trajectory',
        trajetoriaSub='The same step, your first pass next to the latest one. No score, no comparison: just your path.',
        primeira='First pass', recente='Latest',
        mTentativas='Attempts to pass', mDicas='Hints revealed', mExplicacao='Explanation',
        mTempo='Time to pass', mPeer='Talks with the Peer', de2='of 2', minutos='min',
        dJul2='Jul 2', dSet18='Sep 18',
        nivelFund='Foundations', nivelJunior='Junior', nivelPleno='Mid-level', nivelSenior='Senior',
        voltarEvolucao='Progress',
        caminhoTit='Path in the tracks', caminhoSub='This competency’s steps in your tracks, level by level.',
        estFeita='done', estPulada='skipped by the entry exercise', estCoberta='covered by your level',
        seniorSem='Senior has no steps in the tracks yet. When it does, they show up here.',
        historicoTit='Level history',
        hPlenoConf='Mid-level confirmed', hPlenoConfTxt='Three mid-level solutions with an explanation that shows the why.',
        hPartida='Starting point: Junior', hPartidaTxt='Your first confirmed level. From here on, the line only goes up.',
        dAgo='Aug 14',
        vazioSub='No exercise submitted yet. Each competency shows the level you declared at first access, until an exercise confirms it.',
        vazioTempoTit='Over time and trajectory',
        vazioTempoTxt='Your history starts at your first confirmed level. After that, your level shows up here week by week, along with your first pass, the baseline for the next ones.',
        comecarPrimeiro='Start the first exercise',
    ),
    'es-ES': dict(
        evTitulo='Evolución',
        evSub='Siempre frente a tu propio historial. El nivel solo sube, y nada aquí te compara con otra persona.',
        comoMedido='Cómo se mide el nivel',
        competencias='Tus competencias', grupoJs='JavaScript', grupoArq='Arquitectura',
        colComp='Competencia', colNivel='Nivel', colConfirmado='Confirmado', colDeclarado='Declarado', colProximo='Próximo nivel',
        confirmadoSuf='confirmado', declaradoSuf='declarado', naoConfirmado='aún sin confirmar',
        falta='falta', faltam='faltan', etapa='etapa', etapas='etapas', semEtapas='sin etapas aún',
        noTopo='en el último nivel',
        nasTrilhas='En las rutas', feitas='hechas', puladas='saltadas por el ejercicio de entrada',
        cobertas='cubiertas por tu nivel', pendentes='pendientes',
        noTempo='En el tiempo',
        noTempoSub='El nivel confirmado de cada competencia, semana a semana. La línea empieza en tu punto de partida y solo sube.',
        legPartida='punto de partida', legConfirmacao='confirmación',
        jul='jul', ago='ago', set='sept',
        trajetoria='Trayectoria',
        trajetoriaSub='La misma etapa, la primera aprobación junto a la más reciente. Sin nota ni comparación: solo tu camino.',
        primeira='Primera aprobación', recente='Más reciente',
        mTentativas='Intentos hasta pasar', mDicas='Pistas reveladas', mExplicacao='Explicación',
        mTempo='Tiempo hasta pasar', mPeer='Conversaciones con el Peer', de2='de 2', minutos='min',
        dJul2='2 jul', dSet18='18 sept',
        nivelFund='Fundamentos', nivelJunior='Junior', nivelPleno='nivel intermedio', nivelSenior='Senior',
        voltarEvolucao='Evolución',
        caminhoTit='Camino en la ruta', caminhoSub='Las etapas de esta competencia en tus rutas, nivel por nivel.',
        estFeita='hecha', estPulada='saltada por el ejercicio de entrada', estCoberta='cubierta por tu nivel',
        seniorSem='Senior todavía no tiene etapas en las rutas. Cuando las tenga, aparecen aquí.',
        historicoTit='Historial del nivel',
        hPlenoConf='nivel intermedio confirmado', hPlenoConfTxt='Tres soluciones de nivel intermedio con una explicación que muestra el porqué.',
        hPartida='Punto de partida: Junior', hPartidaTxt='Tu primer nivel confirmado. A partir de aquí, la línea solo sube.',
        dAgo='14 ago',
        vazioSub='Aún sin ejercicio enviado. Cada competencia muestra el nivel que declaraste en el primer acceso, hasta que un ejercicio lo confirme.',
        vazioTempoTit='En el tiempo y trayectoria',
        vazioTempoTxt='Tu historial empieza en tu primer nivel confirmado. Después, aquí aparecen el nivel semana a semana y tu primera aprobación, que se vuelve el punto de comparación de las siguientes.',
        comecarPrimeiro='Empezar el primer ejercicio',
    ),
}
