# Textos da tela do exercício de arquitetura (a bancada), nos três idiomas da web.
# Plano: swell-docs/muriki-code-platform/features/exercicio-arquitetura.

TEXTOS = {
    'pt-BR': dict(
        trilhaArq='Arquitetura', titulo='Encurtador de links', chipSD='System Design', nivel='nível Pleno',
        andamento='em andamento', salvo='salvo há 5 s', continuarIde='Continuar na IDE', enviar='Enviar solução',
        enunciado='Enunciado',
        enunciadoTexto='Desenhe um encurtador de links como o bit.ly: a pessoa manda uma URL longa e recebe um código curto. Quem abre o código é levado à URL original.',
        precisa='O que precisa acontecer',
        req1='10 mil redirecionamentos por segundo, 100 links novos por segundo.',
        req2='Redirecionar responde em menos de 50 ms.',
        req3='Cada acesso é contado, sem atrasar o redirecionamento.',
        explique='Explique sua solução', vaiAvaliacao='vai para a avaliação',
        pergunta='Por que o seu desenho aguenta os redirecionamentos?',
        placeholder='Escreva com as suas palavras. Não precisa ser longo.',
        nota='Entra na avaliação e no seu perfil de System Design.',
        dicas='Dicas', dicasDisp='3 dicas disponíveis', pedirDica='Pedir dica',
        pecas='Peças', regras='Regras', passam='2 de 3 passam',
        pCliente='Cliente', pApi='API', pBanco='Banco', pCache='Cache', pFila='Fila', pWorker='Worker', pCdn='CDN',
        r1='O cliente só fala com a API', r2='Redirecionar não lê o banco toda vez',
        r3='Os acessos são contados sem atrasar o redirecionamento',
        dicaVerificar='Verifique com ⌘ ↵ para ver as regras',
        chama='chama', le='lê', escreve='escreve', publica='publica', consome='consome',
        renomear='Renomear', apagar='Apagar', verificar='Verificar',
        nNavegador='Navegador', nApi='API de links', nRedis='Redis', nPostgres='Postgres', rotuloCache='código → URL',
        status='4 peças · 3 ligações', atalho='⌘ ↵ verifica', bancada='Bancada do diagrama',
    ),
    'en-US': dict(
        trilhaArq='Architecture', titulo='Link shortener', chipSD='System Design', nivel='Mid-level',
        andamento='in progress', salvo='saved 5 s ago', continuarIde='Continue in your IDE', enviar='Submit solution',
        enunciado='Problem',
        enunciadoTexto='Design a link shortener like bit.ly: a person sends a long URL and gets a short code back. Whoever opens the code lands on the original URL.',
        precisa='What needs to happen',
        req1='10k redirects per second, 100 new links per second.',
        req2='A redirect answers in under 50 ms.',
        req3='Every visit is counted without slowing the redirect.',
        explique='Explain your solution', vaiAvaliacao='goes into the evaluation',
        pergunta='Why does your design handle the redirects?',
        placeholder='Use your own words. It doesn’t need to be long.',
        nota='Goes into the evaluation and your System Design profile.',
        dicas='Hints', dicasDisp='3 hints available', pedirDica='Ask for a hint',
        pecas='Pieces', regras='Rules', passam='2 of 3 pass',
        pCliente='Client', pApi='API', pBanco='Database', pCache='Cache', pFila='Queue', pWorker='Worker', pCdn='CDN',
        r1='The client only talks to the API', r2='A redirect doesn’t read the database every time',
        r3='Visits are counted without slowing the redirect',
        dicaVerificar='Check with ⌘ ↵ to see the rules',
        chama='calls', le='reads', escreve='writes', publica='publishes', consome='consumes',
        renomear='Rename', apagar='Delete', verificar='Check',
        nNavegador='Browser', nApi='Links API', nRedis='Redis', nPostgres='Postgres', rotuloCache='code → URL',
        status='4 pieces · 3 connections', atalho='⌘ ↵ checks', bancada='Diagram workbench',
    ),
    'es-ES': dict(
        trilhaArq='Arquitectura', titulo='Acortador de enlaces', chipSD='System Design', nivel='nivel intermedio',
        andamento='en curso', salvo='guardado hace 5 s', continuarIde='Seguir en el IDE', enviar='Enviar solución',
        enunciado='Enunciado',
        enunciadoTexto='Diseña un acortador de enlaces como bit.ly: la persona envía una URL larga y recibe un código corto. Quien abre el código llega a la URL original.',
        precisa='Lo que tiene que pasar',
        req1='10 mil redirecciones por segundo, 100 enlaces nuevos por segundo.',
        req2='Una redirección responde en menos de 50 ms.',
        req3='Cada visita se cuenta sin retrasar la redirección.',
        explique='Explica tu solución', vaiAvaliacao='va a la evaluación',
        pergunta='¿Por qué tu diseño aguanta las redirecciones?',
        placeholder='Escríbelo con tus palabras. No hace falta que sea largo.',
        nota='Entra en la evaluación y en tu perfil de System Design.',
        dicas='Pistas', dicasDisp='3 pistas disponibles', pedirDica='Pedir pista',
        pecas='Piezas', regras='Reglas', passam='2 de 3 pasan',
        pCliente='Cliente', pApi='API', pBanco='Base de datos', pCache='Caché', pFila='Cola', pWorker='Worker', pCdn='CDN',
        r1='El cliente solo habla con la API', r2='Redirigir no lee la base de datos cada vez',
        r3='Las visitas se cuentan sin retrasar la redirección',
        dicaVerificar='Verifica con ⌘ ↵ para ver las reglas',
        chama='llama', le='lee', escreve='escribe', publica='publica', consome='consume',
        renomear='Renombrar', apagar='Borrar', verificar='Verificar',
        nNavegador='Navegador', nApi='API de enlaces', nRedis='Redis', nPostgres='Postgres', rotuloCache='código → URL',
        status='4 piezas · 3 conexiones', atalho='⌘ ↵ verifica', bancada='Banco del diagrama',
    ),
}
