# Textos de Trilhas, do catálogo de Exercícios e do Peer na web. Somam-se ao COMUM.
# O formato das trilhas ainda está em aberto na visão do produto; aqui vai a proposta: uma trilha é
# uma sequência de etapas (exercícios, com uma leitura curta de vez em quando) numa competência, que
# o Learning adapta pelo perfil — repete o tema com outro exercício ou avança.

TRILHAS = {
    'pt-BR': dict(
        tTitulo='Trilhas',
        tSub='Uma sequência de exercícios por competência, no seu nível. A próxima etapa muda com o que você mostra.',
        continuar='Continue de onde parou', proxEtapa='Próxima etapa', continuarBtn='Continuar',
        filtroTodas='Todas', filtroAndamento='Em andamento', filtroRecomendadas='Para você', filtroFeitas='Concluídas',
        etapas='etapas', feitas='feitas', horas='h no total', naoIniciada='Não iniciada', comecar='Começar',
        recomendada='para você', porQue='Seu nível em Testing está a confirmar',
        t1='Testes que dão confiança', t1Txt='Casos de borda, relógio falso e testes que não quebram à toa.',
        t2='Achar o bug antes do usuário', t2Txt='Ler o erro, reduzir o caso e provar a correção com um teste.',
        t3='Tipos que documentam', t3Txt='Tipos que dizem o que a função aceita e impedem o erro de compilar.',
        t4='APIs que não quebram quem usa', t4Txt='Versão, erros previsíveis e contratos que aguentam mudança.',
        t5='Fronteiras e dependências', t5Txt='Onde cortar um sistema e para que lado cada parte depende.',
        t6='O básico que evita incidente', t6Txt='Entrada que não se confia, segredo fora do código e o mínimo de permissão.',
        e1='Testar com relógio falso', e1Txt='A etapa de agora: o seu último envio errou os casos com fuso horário.',
        so_pro='no Pro',
        miniTit='O caminho', miniAqui='você está aqui', miniComece='comece aqui', miniVer='Ver o mapa',
    ),
    'en-US': dict(
        tTitulo='Tracks',
        tSub='A sequence of exercises per competency, at your level. The next step changes with what you show.',
        continuar='Pick up where you left off', proxEtapa='Next step', continuarBtn='Continue',
        filtroTodas='All', filtroAndamento='In progress', filtroRecomendadas='For you', filtroFeitas='Completed',
        etapas='steps', feitas='done', horas='h in total', naoIniciada='Not started', comecar='Start',
        recomendada='for you', porQue='Your Testing level is to be confirmed',
        t1='Tests you can trust', t1Txt='Edge cases, fake clocks and tests that don’t break for no reason.',
        t2='Find the bug before the user does', t2Txt='Read the error, shrink the case and prove the fix with a test.',
        t3='Types that document', t3Txt='Types that say what a function accepts and stop the bug from compiling.',
        t4='APIs that don’t break their callers', t4Txt='Versioning, predictable errors and contracts that survive change.',
        t5='Boundaries and dependencies', t5Txt='Where to cut a system and which way each part depends.',
        t6='The basics that prevent incidents', t6Txt='Untrusted input, secrets out of the code and least privilege.',
        e1='Testing with a fake clock', e1Txt='The step for now: your last submission missed the time zone cases.',
        so_pro='on Pro',
        miniTit='The path', miniAqui='you are here', miniComece='start here', miniVer='See the map',
    ),
    'es-ES': dict(
        tTitulo='Rutas',
        tSub='Una secuencia de ejercicios por competencia, a tu nivel. El siguiente paso cambia con lo que demuestras.',
        continuar='Sigue donde lo dejaste', proxEtapa='Siguiente paso', continuarBtn='Continuar',
        filtroTodas='Todas', filtroAndamento='En curso', filtroRecomendadas='Para ti', filtroFeitas='Terminadas',
        etapas='pasos', feitas='hechos', horas='h en total', naoIniciada='Sin empezar', comecar='Empezar',
        recomendada='para ti', porQue='Tu nivel en Testing está por confirmar',
        t1='Pruebas que dan confianza', t1Txt='Casos límite, reloj falso y pruebas que no se rompen porque sí.',
        t2='Encontrar el bug antes que el usuario', t2Txt='Leer el error, reducir el caso y probar el arreglo con una prueba.',
        t3='Tipos que documentan', t3Txt='Tipos que dicen qué acepta la función e impiden que el error compile.',
        t4='APIs que no rompen a quien las usa', t4Txt='Versiones, errores previsibles y contratos que aguantan cambios.',
        t5='Fronteras y dependencias', t5Txt='Dónde cortar un sistema y hacia qué lado depende cada parte.',
        t6='Lo básico que evita incidentes', t6Txt='Entrada que no se confía, secretos fuera del código y el mínimo de permisos.',
        e1='Probar con reloj falso', e1Txt='El paso de ahora: tu último envío falló los casos con zona horaria.',
        so_pro='en Pro',
        miniTit='El camino', miniAqui='estás aquí', miniComece='empieza aquí', miniVer='Ver el mapa',
    ),
}

TRILHA = {
    'pt-BR': dict(
        dTitulo='Testes que dão confiança',
        dSub='8 etapas em Testing, de Pleno para Senior. Uns 3 h no total, no seu ritmo.',
        mapa='O caminho', feita='feita', agora='agora', depois='depois', leitura='leitura curta', exercicio='exercício',
        min='min', nota='nota',
        s1='Casos de borda primeiro', s2='Nomear o que o teste prova', s3='Converter duração em texto para minutos',
        s4='Testar com relógio falso', s5='Isolar sem mockar tudo', s6='Teste que falha pelo motivo certo',
        s7='Propriedades em vez de exemplos', s8='Revisar a suíte de outra pessoa',
        repetiu='O Code repetiu o tema', repetiuTxt='O seu envio de “Converter duração” errou os casos com fuso horário. Esta etapa volta nisso com outro problema antes de seguir.',
        seuNivel='Seu nível em Testing', declarado='Declarado', observado='Observado', aConfirmar='a confirmar',
        nivelTxt='Duas etapas com nota alta confirmam Pleno. As três últimas contam para Senior.',
        conta='O que esta trilha conta', contaTxt='Cada etapa enviada vira evidência em Testing; algumas também em Debugging.',
        sair='Sair da trilha', sairTxt='O progresso fica guardado.',
    ),
    'en-US': dict(
        dTitulo='Tests you can trust',
        dSub='8 steps in Testing, from Mid-level to Senior. About 3 h in total, at your pace.',
        mapa='The path', feita='done', agora='now', depois='later', leitura='short read', exercicio='exercise',
        min='min', nota='score',
        s1='Edge cases first', s2='Name what the test proves', s3='Convert a text duration into minutes',
        s4='Testing with a fake clock', s5='Isolate without mocking everything', s6='A test that fails for the right reason',
        s7='Properties instead of examples', s8='Review someone else’s suite',
        repetiu='Code repeated the topic', repetiuTxt='Your “Convert a duration” submission missed the time zone cases. This step comes back to it with another problem before moving on.',
        seuNivel='Your Testing level', declarado='Declared', observado='Observed', aConfirmar='to be confirmed',
        nivelTxt='Two steps with a high score confirm Mid-level. The last three count toward Senior.',
        conta='What this track counts', contaTxt='Every submitted step becomes evidence in Testing; some also in Debugging.',
        sair='Leave the track', sairTxt='Your progress is saved.',
    ),
    'es-ES': dict(
        dTitulo='Pruebas que dan confianza',
        dSub='8 pasos en Testing, de Intermedio a Senior. Unas 3 h en total, a tu ritmo.',
        mapa='El camino', feita='hecho', agora='ahora', depois='después', leitura='lectura corta', exercicio='ejercicio',
        min='min', nota='nota',
        s1='Primero los casos límite', s2='Nombrar lo que prueba la prueba', s3='Convertir una duración en texto a minutos',
        s4='Probar con reloj falso', s5='Aislar sin simularlo todo', s6='Una prueba que falla por el motivo correcto',
        s7='Propiedades en vez de ejemplos', s8='Revisar la suite de otra persona',
        repetiu='Code repitió el tema', repetiuTxt='Tu envío de “Convertir una duración” falló los casos con zona horaria. Este paso vuelve a eso con otro problema antes de seguir.',
        seuNivel='Tu nivel en Testing', declarado='Declarado', observado='Observado', aConfirmar='por confirmar',
        nivelTxt='Dos pasos con nota alta confirman Intermedio. Los tres últimos cuentan para Senior.',
        conta='Lo que cuenta esta ruta', contaTxt='Cada paso enviado se vuelve evidencia en Testing; algunos también en Debugging.',
        sair='Dejar la ruta', sairTxt='El progreso queda guardado.',
    ),
}

CATALOGO = {
    'pt-BR': dict(
        cTitulo='Exercícios',
        cSub='Problemas com testes, no navegador ou na IDE. Cada envio conta para o seu perfil.',
        busca='Buscar exercício', fCompetencia='Competência', fNivel='Nível', fLinguagem='Linguagem',
        abaTodos='Todos', abaParaVoce='Para você', abaAndamento='Em andamento', abaFeitos='Feitos',
        uso='exercícios este mês', usoDe='de',
        novo='Novo', andamento='Em andamento', feito='Feito', proBloq='No Pro',
        abrir='Abrir', continuar='Continuar', refazer='Refazer', verPro='Ver o Pro',
        x1='Testar com relógio falso', x2='Converter duração em texto para minutos', x3='Achar o vazamento no cache',
        x4='Paginação por cursor sem pular itens', x5='Validar entrada sem confiar no cliente', x6='Tipar um evento com união discriminada',
        x7='Retry com recuo exponencial', x8='Migração sem derrubar a tabela',
        daTrilha='da trilha', naoTem='Nada com esses filtros.',
    ),
    'en-US': dict(
        cTitulo='Exercises',
        cSub='Problems with tests, in the browser or in your IDE. Every submission counts toward your profile.',
        busca='Search exercises', fCompetencia='Competency', fNivel='Level', fLinguagem='Language',
        abaTodos='All', abaParaVoce='For you', abaAndamento='In progress', abaFeitos='Done',
        uso='exercises this month', usoDe='of',
        novo='New', andamento='In progress', feito='Done', proBloq='On Pro',
        abrir='Open', continuar='Continue', refazer='Redo', verPro='See Pro',
        x1='Testing with a fake clock', x2='Convert a text duration into minutes', x3='Find the leak in the cache',
        x4='Cursor pagination without skipping items', x5='Validate input without trusting the client', x6='Type an event with a discriminated union',
        x7='Retry with exponential backoff', x8='A migration that doesn’t lock the table',
        daTrilha='from the track', naoTem='Nothing matches these filters.',
    ),
    'es-ES': dict(
        cTitulo='Ejercicios',
        cSub='Problemas con pruebas, en el navegador o en el IDE. Cada envío cuenta para tu perfil.',
        busca='Buscar ejercicio', fCompetencia='Competencia', fNivel='Nivel', fLinguagem='Lenguaje',
        abaTodos='Todos', abaParaVoce='Para ti', abaAndamento='En curso', abaFeitos='Hechos',
        uso='ejercicios este mes', usoDe='de',
        novo='Nuevo', andamento='En curso', feito='Hecho', proBloq='En Pro',
        abrir='Abrir', continuar='Continuar', refazer='Rehacer', verPro='Ver Pro',
        x1='Probar con reloj falso', x2='Convertir una duración en texto a minutos', x3='Encontrar la fuga en la caché',
        x4='Paginación por cursor sin saltar elementos', x5='Validar la entrada sin confiar en el cliente', x6='Tipar un evento con unión discriminada',
        x7='Reintento con espera exponencial', x8='Una migración que no bloquea la tabla',
        daTrilha='de la ruta', naoTem='Nada con estos filtros.',
    ),
}

PEER_WEB = {
    'pt-BR': dict(
        pTitulo='Peer',
        pSub='O que o Peer conversou com você na IDE, e onde ele pode olhar.',
        conversas='Conversas', hoje='Hoje', ontem='Ontem', semana='Esta semana',
        c1='Por que o teste passa sozinho e falha na suíte?', c2='Relógio falso com setTimeout', c3='Nome do teste de fuso',
        c4='Onde colocar a validação do cupom', c5='Erro de tipo no reducer',
        pExercicios='exercícios do Muriki', pApi='api-pagamentos',
        m1='O teste de fuso passa quando roda sozinho e falha na suíte. O que muda entre as duas execuções?',
        m2='Acho que é a ordem. Outro teste mexe no fuso e não volta.',
        m3='Faz sentido. Como você provaria isso sem ler todos os testes?',
        m4='Rodando só os dois juntos, nas duas ordens?',
        m5='Isso. Se falhar numa ordem só, o vazamento está no primeiro. Quer uma dica de onde ele guarda o fuso?',
        evidencia='virou evidência em Debugging', trecho='o trecho que o Peer viu',
        perguntar='Pergunte ao Peer', perguntarNota='Aqui o Peer não vê o seu código. Na IDE, ele vê só o trecho em volta do que você está fazendo.',
        enviar='Enviar',
        projetos='Onde o Peer olha', projetosTxt='Ligado por projeto. Arquivos do .gitignore, .env e segredos nunca são lidos.',
        ligado='ligado', desligado='desligado', padrao='padrão', sitePessoal='site-pessoal',
        usoPeer='Mensagens do Peer este mês', usoDe='de',
        ide='Conectado ao VS Code', ideTxt='há 2 h, neste computador', gerenciar='Gerenciar',
    ),
    'en-US': dict(
        pTitulo='Peer',
        pSub='What the Peer talked about with you in your IDE, and where it may look.',
        conversas='Conversations', hoje='Today', ontem='Yesterday', semana='This week',
        c1='Why does the test pass alone and fail in the suite?', c2='Fake clock with setTimeout', c3='Naming the time zone test',
        c4='Where to put the coupon validation', c5='Type error in the reducer',
        pExercicios='Muriki exercises', pApi='payments-api',
        m1='The time zone test passes when it runs alone and fails in the suite. What changes between the two runs?',
        m2='I think it’s the order. Another test changes the time zone and doesn’t restore it.',
        m3='Makes sense. How would you prove it without reading every test?',
        m4='By running just those two together, in both orders?',
        m5='Exactly. If it fails in one order only, the leak is in the first one. Want a hint about where it keeps the time zone?',
        evidencia='became evidence in Debugging', trecho='the snippet the Peer saw',
        perguntar='Ask the Peer', perguntarNota='Here the Peer can’t see your code. In your IDE it only sees the snippet around what you’re doing.',
        enviar='Send',
        projetos='Where the Peer looks', projetosTxt='On per project. .gitignore files, .env and secrets are never read.',
        ligado='on', desligado='off', padrao='default', sitePessoal='personal-site',
        usoPeer='Peer messages this month', usoDe='of',
        ide='Connected to VS Code', ideTxt='2 h ago, on this computer', gerenciar='Manage',
    ),
    'es-ES': dict(
        pTitulo='Peer',
        pSub='Lo que el Peer habló contigo en el IDE, y dónde puede mirar.',
        conversas='Conversaciones', hoje='Hoy', ontem='Ayer', semana='Esta semana',
        c1='¿Por qué la prueba pasa sola y falla en la suite?', c2='Reloj falso con setTimeout', c3='Nombre de la prueba de zona horaria',
        c4='Dónde poner la validación del cupón', c5='Error de tipo en el reducer',
        pExercicios='ejercicios de Muriki', pApi='api-pagos',
        m1='La prueba de zona horaria pasa cuando corre sola y falla en la suite. ¿Qué cambia entre las dos ejecuciones?',
        m2='Creo que es el orden. Otra prueba cambia la zona horaria y no la restaura.',
        m3='Tiene sentido. ¿Cómo lo probarías sin leer todas las pruebas?',
        m4='¿Corriendo solo esas dos juntas, en los dos órdenes?',
        m5='Eso. Si falla en un solo orden, la fuga está en la primera. ¿Quieres una pista de dónde guarda la zona horaria?',
        evidencia='se volvió evidencia en Debugging', trecho='el fragmento que vio el Peer',
        perguntar='Pregúntale al Peer', perguntarNota='Aquí el Peer no ve tu código. En el IDE solo ve el fragmento alrededor de lo que haces.',
        enviar='Enviar',
        projetos='Dónde mira el Peer', projetosTxt='Activado por proyecto. Los archivos del .gitignore, .env y secretos nunca se leen.',
        ligado='activado', desligado='desactivado', padrao='por defecto', sitePessoal='sitio-personal',
        usoPeer='Mensajes del Peer este mes', usoDe='de',
        ide='Conectado a VS Code', ideTxt='hace 2 h, en este equipo', gerenciar='Gestionar',
    ),
}

# O mapa da trilha (a visão principal) e as boas-vindas às trilhas: o modal com o fundo desfocado que
# monta o começo pelo que a pessoa contou no primeiro acesso (experiência, linguagens, objetivos).
MAPA = {
    'pt-BR': dict(
        vMapa='Mapa', vLista='Lista', vcAqui='você está aqui',
        r1='Fundamentos', r2='Isolar e confiar', r3='Suíte que se defende',
        marcoPleno='confirma Pleno', marcoSenior='conta para Senior',
        agoraTit='Etapa 4 de 8',
    ),
    'en-US': dict(
        vMapa='Map', vLista='List', vcAqui='you are here',
        r1='Foundations', r2='Isolate and trust', r3='A suite that defends itself',
        marcoPleno='confirms Mid-level', marcoSenior='counts toward Senior',
        agoraTit='Step 4 of 8',
    ),
    'es-ES': dict(
        vMapa='Mapa', vLista='Lista', vcAqui='estás aquí',
        r1='Fundamentos', r2='Aislar y confiar', r3='Una suite que se defiende',
        marcoPleno='confirma Intermedio', marcoSenior='cuenta para Senior',
        agoraTit='Paso 4 de 8',
    ),
}

BOAS_VINDAS = {
    'pt-BR': dict(
        expContou='De 2 a 5 anos',
        bvRotulo='Trilhas · primeira vez',
        bvP1='Seu ponto de partida', bvP2='Suas trilhas', bvP3='Como a trilha anda',
        bv1Tit='Montamos o seu começo, Rafael.', bv1Txt='Pelo que você contou no primeiro acesso:',
        bvExp='Experiência', bvLing='Linguagens', bvObj='Objetivos', bvAprender='Aprender', bvRevisar='Revisar código',
        bvComeco='Começamos por Testing em TypeScript, no nível Pleno. Depois, tipos e arquitetura.',
        bv2Tit='Suas três primeiras trilhas', bv2Txt='Na ordem que faz sentido para você. Ela muda com o que você mostrar.',
        bvComecaAqui='começa aqui', bvDepois='depois',
        bv3Tit='Como a trilha anda', bv3Txt='Você não precisa escolher o próximo passo.',
        bvI1='Cada etapa é um exercício com testes', bvI1Txt='Uns 20 minutos, no navegador ou na IDE.',
        bvI2='O Code repete ou avança', bvI2Txt='Errou um tema? Ele volta com outro problema antes de seguir.',
        bvI3='Tudo conta para o seu perfil', bvI3Txt='Duas etapas com nota alta já confirmam o seu nível.',
        bvPular='Pular', bvVoltar='Voltar', bvContinuar='Continuar', bvAbrir='Abrir a trilha',
        bvEtapas='etapas',
    ),
    'en-US': dict(
        expContou='2 to 5 years',
        bvRotulo='Tracks · first time',
        bvP1='Your starting point', bvP2='Your tracks', bvP3='How a track moves',
        bv1Tit='We set up your start, Rafael.', bv1Txt='From what you told us on your first access:',
        bvExp='Experience', bvLing='Languages', bvObj='Goals', bvAprender='Learn', bvRevisar='Review code',
        bvComeco='We start with Testing in TypeScript, at Mid-level. Then types and architecture.',
        bv2Tit='Your first three tracks', bv2Txt='In the order that makes sense for you. It changes with what you show.',
        bvComecaAqui='starts here', bvDepois='next',
        bv3Tit='How a track moves', bv3Txt='You don’t need to pick the next step.',
        bvI1='Every step is an exercise with tests', bvI1Txt='About 20 minutes, in the browser or in your IDE.',
        bvI2='Code repeats or moves on', bvI2Txt='Missed a topic? It comes back with another problem before moving on.',
        bvI3='Everything counts toward your profile', bvI3Txt='Two steps with a high score already confirm your level.',
        bvPular='Skip', bvVoltar='Back', bvContinuar='Continue', bvAbrir='Open the track',
        bvEtapas='steps',
    ),
    'es-ES': dict(
        expContou='De 2 a 5 años',
        bvRotulo='Rutas · primera vez',
        bvP1='Tu punto de partida', bvP2='Tus rutas', bvP3='Cómo avanza la ruta',
        bv1Tit='Armamos tu comienzo, Rafael.', bv1Txt='Por lo que contaste en tu primer acceso:',
        bvExp='Experiencia', bvLing='Lenguajes', bvObj='Objetivos', bvAprender='Aprender', bvRevisar='Revisar código',
        bvComeco='Empezamos por Testing en TypeScript, en nivel Intermedio. Después, tipos y arquitectura.',
        bv2Tit='Tus tres primeras rutas', bv2Txt='En el orden que tiene sentido para ti. Cambia con lo que demuestres.',
        bvComecaAqui='empieza aquí', bvDepois='después',
        bv3Tit='Cómo avanza la ruta', bv3Txt='No necesitas elegir el siguiente paso.',
        bvI1='Cada paso es un ejercicio con pruebas', bvI1Txt='Unos 20 minutos, en el navegador o en el IDE.',
        bvI2='Code repite o avanza', bvI2Txt='¿Fallaste un tema? Vuelve con otro problema antes de seguir.',
        bvI3='Todo cuenta para tu perfil', bvI3Txt='Dos pasos con nota alta ya confirman tu nivel.',
        bvPular='Saltar', bvVoltar='Volver', bvContinuar='Continuar', bvAbrir='Abrir la ruta',
        bvEtapas='pasos',
    ),
}

# Trilhas antes da primeira etapa: nada em andamento. O topo vira "por onde começar", montado pelo
# primeiro acesso, e as recomendadas vêm primeiro, na ordem.
TRILHAS_VAZIA = {
    'pt-BR': dict(
        vzRotulo='Por onde começar', vzPorque='Pelo seu primeiro acesso: programa de 2 a 5 anos, TypeScript e Python.',
        vzMeta='8 etapas · uns 3 h · a primeira leva 8 min', vzComecar='Começar a trilha', vzRever='Ver as boas-vindas de novo',
        vz1='1ª para você', vz2='2ª para você', vz3='3ª para você',
    ),
    'en-US': dict(
        vzRotulo='Where to start', vzPorque='From your first access: coding for 2 to 5 years, TypeScript and Python.',
        vzMeta='8 steps · about 3 h · the first takes 8 min', vzComecar='Start the track', vzRever='See the welcome again',
        vz1='1st for you', vz2='2nd for you', vz3='3rd for you',
    ),
    'es-ES': dict(
        vzRotulo='Por dónde empezar', vzPorque='Por tu primer acceso: programas de 2 a 5 años, TypeScript y Python.',
        vzMeta='8 pasos · unas 3 h · el primero lleva 8 min', vzComecar='Empezar la ruta', vzRever='Ver la bienvenida de nuevo',
        vz1='1.ª para ti', vz2='2.ª para ti', vz3='3.ª para ti',
    ),
}
