# Textos de Minha conta: meus dados, aprendizado, segurança e plano. Somam-se ao COMUM e, na aba
# Aprendizado, às PREFERENCIAS do primeiro acesso (experiência, linguagens e objetivos).

MINHA_CONTA = {
    'pt-BR': dict(
        contaTitulo='Minha conta',
        contaSub='Seus dados, o que você quer aprender, a segurança e o plano do Code. A conta Muriki é a mesma no Code e no Platform.',
        abasAria='Seções da conta', abaDados='Meus dados', abaAprendizado='Aprendizado', abaSeguranca='Segurança', abaPlano='Plano',
        cancelar='Cancelar', salvar='Salvar alterações', descartar='Descartar', opcional='opcional',
        # meus dados
        dadosTit='Dados pessoais', dadosSub='Valem para a sua conta Muriki inteira, no Code e no Platform.',
        apelido='Como quer ser chamado', nome='Nome completo', telefone='Telefone', telefonePh='(11) 91234-5678',
        telefoneNota='O atual termina em 5678. Para trocar, digite o novo.', removerTelefone='Remover telefone',
        cpf='CPF', cpfNota='O CPF não muda por aqui: é um teste grátis do Pro por CPF. Está errado? Fale com o suporte.',
        emailTit='Email', emailSub='É com ele que você entra e recebe os avisos da conta.', verificado='Verificado', trocarEmail='Trocar email',
        novoEmail='Email novo', novoEmailPh='voce@exemplo.com', enviarLink='Enviar link',
        trocarNota='Antes, pedimos a sua senha. Se o email puder ser usado, mandamos um link para ele, que vale por 30 minutos. Até você abrir, nada muda.',
        pendenteA='Aguardando a confirmação em', pendenteB='O link vale até as 22:39. Ao abrir, todas as sessões caem e você entra com o email novo.', reenviar='Reenviar link',
        termosTit='Termos e privacidade',
        termosTxt='Você aceitou os termos de uso e a política de privacidade de 1º de setembro de 2026 em 21 de setembro de 2026.',
        verTermos='Termos de uso', verPrivacidade='Política de privacidade',
        excluirTit='Excluir conta', excluirSub='Apaga a sua conta Muriki no Code e no Platform. Não dá para desfazer.', excluir='Excluir minha conta',
        excluirPergunta='Excluir a sua conta Muriki?',
        excluirTxt='Apaga o seu perfil, o perfil de aprendizado, a senha, as passkeys e o segundo fator, no Code e no Platform, e encerra todas as sessões. O Pro é cancelado agora, sem reembolso do período. Não dá para desfazer.',
        confirmeSenha='Para confirmar, digite a sua senha', usarCodigo='Usar o código do app', excluirDefinitivo='Excluir a conta',
        # aprendizado
        aprTit='Perfil de aprendizado', aprSub='Ajuda o Code a escolher trilhas e o Peer a falar no seu nível. Nada aqui é obrigatório.',
        declaradoNota='O declarado da Evolução vem da experiência: mudar aqui muda o declarado de todas as competências. O observado continua vindo das suas evidências.',
        # segurança
        senhaTit='Senha', senhaSub='Trocar a senha encerra as suas outras sessões.', senhaAtual='Senha atual', senhaNova='Senha nova',
        senhaNovaPh='Pelo menos 12 caracteres', senhaReq='De 12 a 128 caracteres, fora de vazamentos conhecidos.', trocarSenha='Trocar senha',
        doisTit='Verificação em duas etapas', doisSub='Ao entrar, além da senha, um código do app autenticador.',
        appAutenticador='App autenticador', ativadaEm='Ativada em 21 de setembro de 2026', ativa='Ativa', desligada='Desligada',
        codigosNovos='Gerar códigos de backup novos', codigosNota='Os códigos novos substituem os antigos, que param de valer.',
        desligar='Desligar', ligar='Ativar',
        ligarNota='Pedimos a sua senha, você escaneia o QR no app e recebe dez códigos de backup, que aparecem uma vez só.',
        passkeysTit='Passkeys', passkeysSub='Entrar com a digital, o rosto ou uma chave de segurança, sem senha nem código.',
        adicionarPasskey='Adicionar passkey', sincronizada='Sincronizada entre aparelhos', nesteAparelho='Só neste aparelho',
        criadaEm='Criada em', pq1='21 de setembro', pq2='24 de setembro', remover='Remover', renomear='Renomear',
        sessoesTit='Sessões', sessoesSub='Onde a sua conta está conectada. Encerrar derruba o acesso naquele aparelho na hora.',
        estaSessao='Esta sessão', encerrar='Encerrar', encerrarOutras='Encerrar as outras', ultimoUso='Último uso',
        sq1='agora', sq2='ontem, 08:12', sq3='18 de setembro, 14:30',
        protegido='Desligar o segundo fator, mexer nas passkeys e excluir a conta pedem para você confirmar que é você.',
        stepTit='Confirme que é você', stepTxt='Para adicionar uma passkey, digite a sua senha. A confirmação vale por 5 minutos.',
        stepSenha='Senha', confirmar='Confirmar',
        # plano
        planoTit='Plano do Code', planoSub='A assinatura do Code é separada da do Platform.',
        situacao='Situação', emTeste='Teste grátis', testeAte='até 1º de outubro de 2026', periodoRot='Período', mensalV='Mensal',
        cobranca='Primeira cobrança', cobrancaV='R$ 49,90 em 1º de outubro',
        portal='Pagamento e faturas', portalNota='Trocar o cartão, baixar faturas e cancelar ficam no portal do Stripe, que abre numa aba nova.',
        verPlanos='Ver planos',
        cancelouNota='Cancelou? O Pro fica até o fim do período pago. Depois você volta ao Starter sem perder histórico nem perfil.',
        # /confirm-email: o link que chega no email novo
        ceConfirmandoTit='Confirmando o seu email novo', ceConfirmandoTxt='Só um instante.',
        ceOkTit='Email trocado', ceOkTxt='A sua conta Muriki agora usa rafael@muriki.dev. Por segurança, todas as sessões foram encerradas: entre de novo com o email novo.',
        ceEntrar='Entrar',
        ceInvalidoTit='Este link não vale mais', ceInvalidoTxt='Links de troca de email valem por 30 minutos e só uma vez. Peça a troca de novo em Minha conta.',
        ceIrConta='Ir para Minha conta',
        ceTomadoTit='Esse email já está em uso', ceTomadoTxt='Outra conta passou a usar rafael@muriki.dev antes da confirmação. O seu email continua o mesmo.',
        # fluxos: adicionar passkey, ativar 2FA, códigos novos, renomear e remover passkey, encerrar sessões
        pkTit='Adicionar passkey', pkSub='A passkey fica guardada no aparelho ou na chave, e só você destrava.',
        pkNome='Nome', pkNomeNota='Para você reconhecer depois. Dá para mudar.', pkOnde='Onde guardar',
        pkEste='Neste aparelho', pkEsteDesc='Touch ID, Face ID ou Windows Hello. Sincroniza pelo iCloud ou pelo Google, se estiver ligado.',
        pkChave='Chave de segurança', pkChaveDesc='Uma chave física, como a YubiKey, pela USB ou por NFC.', pkCriar='Criar passkey',
        pkNavTit='Siga o seu navegador', pkNavTxt='O navegador abriu a janela da passkey. Confirme com a digital, o rosto ou tocando na chave.',
        pkProntaTit='Passkey criada', pkProntaTxt='Da próxima vez, entre com a passkey “MacBook Air”, sem senha nem código.', pronto='Pronto',
        pkCanceladaTit='Nada foi criado', pkCanceladaTxt='A janela do navegador foi fechada ou o tempo acabou. Tente de novo quando quiser.',
        tentarDeNovo='Tentar de novo',
        tfTit='Ativar a verificação em duas etapas', tfP1='Confirmar que é você', tfP2='Ligar o app', tfP3='Guardar os códigos',
        tfSenhaTxt='Digite a sua senha para começar.', continuar='Continuar',
        tfQrTxt='Escaneie com o app autenticador, como o Google Authenticator, o 1Password ou o Authy.',
        tfChave='Não dá para escanear? Digite a chave:', tfCodigoTxt='Depois, digite o código de 6 dígitos que o app mostra.',
        codigoRot='Código', tfInvalido='Código inválido. Confira se o relógio do celular está certo e tente de novo.', tfAtivar='Ativar',
        tfCodigosTxt='Estes dez códigos entram quando você estiver sem o app. Cada um vale uma vez, e esta é a única vez que aparecem.',
        baixarPdf='Baixar PDF', copiar='Copiar', guardei='Guardei os códigos num lugar seguro', concluir='Concluir',
        cnTit='Gerar códigos de backup novos', cnTxt='Os dez códigos atuais param de valer assim que os novos aparecerem. Para confirmar, digite a sua senha.',
        cnGerar='Gerar códigos novos', cnCodigosTxt='Os antigos já não valem. Guarde estes: cada um vale uma vez, e esta é a única vez que aparecem.',
        salvarNome='Salvar', rmTit='Remover a passkey “YubiKey 5C”?',
        rmTxt='Você não vai mais conseguir entrar com ela. A senha, o segundo fator e a outra passkey continuam valendo.', rmBotao='Remover passkey',
        s1Tit='Encerrar a sessão do Safari no iOS?', s1Txt='Esse aparelho sai agora e pede para entrar de novo. As outras sessões continuam.',
        s1Botao='Encerrar sessão', soTit='Encerrar as outras 2 sessões?',
        soTxt='Safari no iOS e Firefox no Windows saem agora e pedem para entrar de novo. Esta sessão continua.', soBotao='Encerrar 2 sessões',
    ),
    'en-US': dict(
        contaTitulo='My account',
        contaSub='Your details, what you want to learn, security and your Code plan. Your Muriki account is the same in Code and Platform.',
        abasAria='Account sections', abaDados='My details', abaAprendizado='Learning', abaSeguranca='Security', abaPlano='Plan',
        cancelar='Cancel', salvar='Save changes', descartar='Discard', opcional='optional',
        dadosTit='Personal details', dadosSub='They apply to your whole Muriki account, in Code and in Platform.',
        apelido='What should we call you', nome='Full name', telefone='Phone', telefonePh='(11) 91234-5678',
        telefoneNota='The current one ends in 5678. To change it, type the new one.', removerTelefone='Remove phone',
        cpf='CPF (Brazilian tax ID)', cpfNota='Your CPF can’t be changed here: it’s one free Pro trial per CPF. Is it wrong? Contact support.',
        emailTit='Email', emailSub='You sign in with it and get account notices there.', verificado='Verified', trocarEmail='Change email',
        novoEmail='New email', novoEmailPh='you@example.com', enviarLink='Send link',
        trocarNota='First we ask for your password. If the email can be used, we send it a link that’s valid for 30 minutes. Nothing changes until you open it.',
        pendenteA='Waiting for confirmation at', pendenteB='The link is valid until 10:39 PM. When you open it, every session signs out and you sign in with the new email.', reenviar='Resend link',
        termosTit='Terms and privacy',
        termosTxt='You accepted the September 1, 2026 terms of use and privacy policy on September 21, 2026.',
        verTermos='Terms of use', verPrivacidade='Privacy policy',
        excluirTit='Delete account', excluirSub='Deletes your Muriki account in Code and in Platform. This can’t be undone.', excluir='Delete my account',
        excluirPergunta='Delete your Muriki account?',
        excluirTxt='This deletes your profile, learning profile, password, passkeys and second factor, in Code and in Platform, and signs out every session. Pro is canceled now, with no refund for the period. This can’t be undone.',
        confirmeSenha='To confirm, type your password', usarCodigo='Use the app code', excluirDefinitivo='Delete account',
        aprTit='Learning profile', aprSub='It helps Code pick tracks and the Peer talk at your level. Nothing here is required.',
        declaradoNota='The declared level in Progress comes from your experience: changing it here changes the declared level of every competency. The observed level still comes from your evidence.',
        senhaTit='Password', senhaSub='Changing your password signs out your other sessions.', senhaAtual='Current password', senhaNova='New password',
        senhaNovaPh='At least 12 characters', senhaReq='12 to 128 characters, not in known breaches.', trocarSenha='Change password',
        doisTit='Two-step verification', doisSub='When you sign in, a code from your authenticator app on top of your password.',
        appAutenticador='Authenticator app', ativadaEm='Turned on September 21, 2026', ativa='On', desligada='Off',
        codigosNovos='Generate new backup codes', codigosNota='The new codes replace the old ones, which stop working.',
        desligar='Turn off', ligar='Turn on',
        ligarNota='We ask for your password, you scan the QR code in the app and get ten backup codes, shown only once.',
        passkeysTit='Passkeys', passkeysSub='Sign in with your fingerprint, face or a security key, with no password or code.',
        adicionarPasskey='Add passkey', sincronizada='Synced across devices', nesteAparelho='This device only',
        criadaEm='Created', pq1='September 21', pq2='September 24', remover='Remove', renomear='Rename',
        sessoesTit='Sessions', sessoesSub='Where your account is signed in. Signing out cuts access on that device right away.',
        estaSessao='This session', encerrar='Sign out', encerrarOutras='Sign out the others', ultimoUso='Last used',
        sq1='now', sq2='yesterday, 8:12 AM', sq3='September 18, 2:30 PM',
        protegido='Turning off the second factor, changing passkeys and deleting the account ask you to confirm it’s you.',
        stepTit='Confirm it’s you', stepTxt='To add a passkey, type your password. The confirmation lasts 5 minutes.',
        stepSenha='Password', confirmar='Confirm',
        planoTit='Code plan', planoSub='The Code subscription is separate from Platform’s.',
        situacao='Status', emTeste='Free trial', testeAte='until October 1, 2026', periodoRot='Billing', mensalV='Monthly',
        cobranca='First charge', cobrancaV='R$49.90 on October 1',
        portal='Payment and invoices', portalNota='Changing your card, downloading invoices and canceling happen in the Stripe portal, which opens in a new tab.',
        verPlanos='See plans',
        cancelouNota='Canceled? Pro stays until the end of the paid period. Then you go back to Starter without losing history or profile.',
        ceConfirmandoTit='Confirming your new email', ceConfirmandoTxt='Just a moment.',
        ceOkTit='Email changed', ceOkTxt='Your Muriki account now uses rafael@muriki.dev. For your security, every session was signed out: sign in again with the new email.',
        ceEntrar='Sign in',
        ceInvalidoTit='This link no longer works', ceInvalidoTxt='Email change links are valid for 30 minutes and only once. Ask for the change again in My account.',
        ceIrConta='Go to My account',
        ceTomadoTit='That email is already in use', ceTomadoTxt='Another account started using rafael@muriki.dev before you confirmed. Your email stays the same.',
        pkTit='Add passkey', pkSub='The passkey stays on the device or the key, and only you can unlock it.',
        pkNome='Name', pkNomeNota='So you recognize it later. You can change it.', pkOnde='Where to keep it',
        pkEste='This device', pkEsteDesc='Touch ID, Face ID or Windows Hello. Syncs through iCloud or Google, if turned on.',
        pkChave='Security key', pkChaveDesc='A physical key, like a YubiKey, over USB or NFC.', pkCriar='Create passkey',
        pkNavTit='Follow your browser', pkNavTxt='Your browser opened the passkey window. Confirm with your fingerprint, your face or by touching the key.',
        pkProntaTit='Passkey created', pkProntaTxt='Next time, sign in with the “MacBook Air” passkey, with no password or code.', pronto='Done',
        pkCanceladaTit='Nothing was created', pkCanceladaTxt='The browser window was closed or timed out. Try again whenever you like.',
        tentarDeNovo='Try again',
        tfTit='Turn on two-step verification', tfP1='Confirm it’s you', tfP2='Connect the app', tfP3='Save the codes',
        tfSenhaTxt='Type your password to start.', continuar='Continue',
        tfQrTxt='Scan it with your authenticator app, like Google Authenticator, 1Password or Authy.',
        tfChave='Can’t scan it? Type the key:', tfCodigoTxt='Then type the 6-digit code the app shows.',
        codigoRot='Code', tfInvalido='Invalid code. Check that your phone’s clock is right and try again.', tfAtivar='Turn on',
        tfCodigosTxt='These ten codes get you in when you don’t have the app. Each works once, and this is the only time they’re shown.',
        baixarPdf='Download PDF', copiar='Copy', guardei='I saved the codes somewhere safe', concluir='Finish',
        cnTit='Generate new backup codes', cnTxt='Your ten current codes stop working as soon as the new ones appear. To confirm, type your password.',
        cnGerar='Generate new codes', cnCodigosTxt='The old ones no longer work. Save these: each works once, and this is the only time they’re shown.',
        salvarNome='Save', rmTit='Remove the “YubiKey 5C” passkey?',
        rmTxt='You won’t be able to sign in with it anymore. Your password, second factor and the other passkey still work.', rmBotao='Remove passkey',
        s1Tit='Sign out Safari on iOS?', s1Txt='That device signs out now and has to sign in again. Your other sessions stay.',
        s1Botao='Sign out session', soTit='Sign out the other 2 sessions?',
        soTxt='Safari on iOS and Firefox on Windows sign out now and have to sign in again. This session stays.', soBotao='Sign out 2 sessions',
    ),
    'es-ES': dict(
        contaTitulo='Mi cuenta',
        contaSub='Tus datos, lo que quieres aprender, la seguridad y el plan de Code. La cuenta Muriki es la misma en Code y en Platform.',
        abasAria='Secciones de la cuenta', abaDados='Mis datos', abaAprendizado='Aprendizaje', abaSeguranca='Seguridad', abaPlano='Plan',
        cancelar='Cancelar', salvar='Guardar cambios', descartar='Descartar', opcional='opcional',
        dadosTit='Datos personales', dadosSub='Valen para toda tu cuenta Muriki, en Code y en Platform.',
        apelido='Cómo quieres que te llamemos', nome='Nombre completo', telefone='Teléfono', telefonePh='(11) 91234-5678',
        telefoneNota='El actual termina en 5678. Para cambiarlo, escribe el nuevo.', removerTelefone='Quitar teléfono',
        cpf='CPF (identificación fiscal de Brasil)', cpfNota='El CPF no se cambia aquí: es una prueba gratis de Pro por CPF. ¿Está mal? Habla con soporte.',
        emailTit='Email', emailSub='Con él entras y recibes los avisos de la cuenta.', verificado='Verificado', trocarEmail='Cambiar email',
        novoEmail='Email nuevo', novoEmailPh='tu@ejemplo.com', enviarLink='Enviar enlace',
        trocarNota='Antes te pedimos la contraseña. Si el email se puede usar, le enviamos un enlace que vale 30 minutos. Hasta que lo abras, nada cambia.',
        pendenteA='Esperando la confirmación en', pendenteB='El enlace vale hasta las 22:39. Al abrirlo, se cierran todas las sesiones y entras con el email nuevo.', reenviar='Reenviar enlace',
        termosTit='Términos y privacidad',
        termosTxt='Aceptaste los términos de uso y la política de privacidad del 1 de septiembre de 2026 el 21 de septiembre de 2026.',
        verTermos='Términos de uso', verPrivacidade='Política de privacidad',
        excluirTit='Eliminar cuenta', excluirSub='Elimina tu cuenta Muriki en Code y en Platform. No se puede deshacer.', excluir='Eliminar mi cuenta',
        excluirPergunta='¿Eliminar tu cuenta Muriki?',
        excluirTxt='Elimina tu perfil, el perfil de aprendizaje, la contraseña, las passkeys y el segundo factor, en Code y en Platform, y cierra todas las sesiones. Pro se cancela ahora, sin reembolso del periodo. No se puede deshacer.',
        confirmeSenha='Para confirmar, escribe tu contraseña', usarCodigo='Usar el código de la app', excluirDefinitivo='Eliminar la cuenta',
        aprTit='Perfil de aprendizaje', aprSub='Ayuda a Code a elegir rutas y al Peer a hablar a tu nivel. Nada aquí es obligatorio.',
        declaradoNota='El nivel declarado de Evolución viene de la experiencia: cambiarla aquí cambia el declarado de todas las competencias. El observado sigue viniendo de tus evidencias.',
        senhaTit='Contraseña', senhaSub='Cambiar la contraseña cierra tus otras sesiones.', senhaAtual='Contraseña actual', senhaNova='Contraseña nueva',
        senhaNovaPh='Al menos 12 caracteres', senhaReq='De 12 a 128 caracteres, fuera de filtraciones conocidas.', trocarSenha='Cambiar contraseña',
        doisTit='Verificación en dos pasos', doisSub='Al entrar, además de la contraseña, un código de la app de autenticación.',
        appAutenticador='App de autenticación', ativadaEm='Activada el 21 de septiembre de 2026', ativa='Activa', desligada='Desactivada',
        codigosNovos='Generar códigos de respaldo nuevos', codigosNota='Los códigos nuevos sustituyen a los antiguos, que dejan de valer.',
        desligar='Desactivar', ligar='Activar',
        ligarNota='Te pedimos la contraseña, escaneas el QR en la app y recibes diez códigos de respaldo, que se muestran una sola vez.',
        passkeysTit='Passkeys', passkeysSub='Entrar con la huella, la cara o una llave de seguridad, sin contraseña ni código.',
        adicionarPasskey='Añadir passkey', sincronizada='Sincronizada entre dispositivos', nesteAparelho='Solo en este dispositivo',
        criadaEm='Creada el', pq1='21 de septiembre', pq2='24 de septiembre', remover='Quitar', renomear='Cambiar nombre',
        sessoesTit='Sesiones', sessoesSub='Dónde está conectada tu cuenta. Cerrar corta el acceso en ese dispositivo al momento.',
        estaSessao='Esta sesión', encerrar='Cerrar', encerrarOutras='Cerrar las demás', ultimoUso='Último uso',
        sq1='ahora', sq2='ayer, 08:12', sq3='18 de septiembre, 14:30',
        protegido='Desactivar el segundo factor, cambiar las passkeys y eliminar la cuenta te piden confirmar que eres tú.',
        stepTit='Confirma que eres tú', stepTxt='Para añadir una passkey, escribe tu contraseña. La confirmación vale 5 minutos.',
        stepSenha='Contraseña', confirmar='Confirmar',
        planoTit='Plan de Code', planoSub='La suscripción de Code es independiente de la de Platform.',
        situacao='Estado', emTeste='Prueba gratis', testeAte='hasta el 1 de octubre de 2026', periodoRot='Periodo', mensalV='Mensual',
        cobranca='Primer cobro', cobrancaV='R$ 49,90 el 1 de octubre',
        portal='Pago y facturas', portalNota='Cambiar la tarjeta, descargar facturas y cancelar se hacen en el portal de Stripe, que se abre en una pestaña nueva.',
        verPlanos='Ver planes',
        cancelouNota='¿Has cancelado? Pro se mantiene hasta el final del periodo pagado. Después vuelves a Starter sin perder historial ni perfil.',
        ceConfirmandoTit='Confirmando tu email nuevo', ceConfirmandoTxt='Un momento.',
        ceOkTit='Email cambiado', ceOkTxt='Tu cuenta Muriki ahora usa rafael@muriki.dev. Por seguridad, se cerraron todas las sesiones: entra de nuevo con el email nuevo.',
        ceEntrar='Entrar',
        ceInvalidoTit='Este enlace ya no vale', ceInvalidoTxt='Los enlaces de cambio de email valen 30 minutos y una sola vez. Pide el cambio de nuevo en Mi cuenta.',
        ceIrConta='Ir a Mi cuenta',
        ceTomadoTit='Ese email ya está en uso', ceTomadoTxt='Otra cuenta empezó a usar rafael@muriki.dev antes de la confirmación. Tu email sigue igual.',
        pkTit='Añadir passkey', pkSub='La passkey queda guardada en el dispositivo o en la llave, y solo tú la desbloqueas.',
        pkNome='Nombre', pkNomeNota='Para que la reconozcas después. Se puede cambiar.', pkOnde='Dónde guardarla',
        pkEste='En este dispositivo', pkEsteDesc='Touch ID, Face ID o Windows Hello. Se sincroniza con iCloud o Google, si está activado.',
        pkChave='Llave de seguridad', pkChaveDesc='Una llave física, como la YubiKey, por USB o NFC.', pkCriar='Crear passkey',
        pkNavTit='Sigue a tu navegador', pkNavTxt='El navegador abrió la ventana de la passkey. Confirma con la huella, la cara o tocando la llave.',
        pkProntaTit='Passkey creada', pkProntaTxt='La próxima vez, entra con la passkey “MacBook Air”, sin contraseña ni código.', pronto='Listo',
        pkCanceladaTit='No se creó nada', pkCanceladaTxt='Se cerró la ventana del navegador o se acabó el tiempo. Inténtalo de nuevo cuando quieras.',
        tentarDeNovo='Intentar de nuevo',
        tfTit='Activar la verificación en dos pasos', tfP1='Confirmar que eres tú', tfP2='Conectar la app', tfP3='Guardar los códigos',
        tfSenhaTxt='Escribe tu contraseña para empezar.', continuar='Continuar',
        tfQrTxt='Escanéalo con tu app de autenticación, como Google Authenticator, 1Password o Authy.',
        tfChave='¿No puedes escanearlo? Escribe la clave:', tfCodigoTxt='Después, escribe el código de 6 dígitos que muestra la app.',
        codigoRot='Código', tfInvalido='Código inválido. Comprueba que la hora del móvil es correcta e inténtalo de nuevo.', tfAtivar='Activar',
        tfCodigosTxt='Estos diez códigos te dejan entrar cuando no tengas la app. Cada uno vale una vez, y esta es la única vez que aparecen.',
        baixarPdf='Descargar PDF', copiar='Copiar', guardei='Guardé los códigos en un lugar seguro', concluir='Terminar',
        cnTit='Generar códigos de respaldo nuevos', cnTxt='Tus diez códigos actuales dejan de valer en cuanto aparezcan los nuevos. Para confirmar, escribe tu contraseña.',
        cnGerar='Generar códigos nuevos', cnCodigosTxt='Los antiguos ya no valen. Guarda estos: cada uno vale una vez, y esta es la única vez que aparecen.',
        salvarNome='Guardar', rmTit='¿Quitar la passkey “YubiKey 5C”?',
        rmTxt='Ya no podrás entrar con ella. La contraseña, el segundo factor y la otra passkey siguen valiendo.', rmBotao='Quitar passkey',
        s1Tit='¿Cerrar la sesión de Safari en iOS?', s1Txt='Ese dispositivo sale ahora y tendrá que entrar de nuevo. Las demás sesiones siguen.',
        s1Botao='Cerrar sesión', soTit='¿Cerrar las otras 2 sesiones?',
        soTxt='Safari en iOS y Firefox en Windows salen ahora y tendrán que entrar de nuevo. Esta sesión sigue.', soBotao='Cerrar 2 sesiones',
    ),
}
