# Textos das páginas de sistema do hub (Code, Backoffice, Platform): sem internet, página não
# encontrada, erro inesperado, sessão expirada e manutenção. O título é editorial, em duas linhas,
# a segunda na cor da marca, como o pitch do login. Nenhuma culpa a pessoa, e toda tela diz o que
# fazer. Somam-se ao COMUM.

SISTEMA = {
    'pt-BR': dict(
        offRot='Sem conexão', offA='Você está', offB='sem internet.',
        offTxt='Precisamos de conexão para salvar o que você faz. O que já foi enviado está guardado.',
        offNota='Assim que a conexão voltar, a página recarrega sozinha.',
        naoRot='Erro 404', naoA='Esta página', naoB='não existe.',
        naoTxt='O link pode estar errado, ou a página mudou de lugar. O resto continua onde estava.',
        erroRot='Erro 500', erroA='Algo deu errado', erroB='do nosso lado.',
        erroTxt='Não foi você. Tente de novo em alguns instantes; se continuar, fale com o suporte e passe o código.',
        erroCodigo='código', suporte='Falar com o suporte',
        sessaoRot='Sessão', sessaoA='Sua sessão', sessaoB='terminou.',
        sessaoTxt='Por segurança, a sessão acaba depois de um tempo sem uso ou quando é encerrada em outro aparelho. Entre de novo e continue de onde parou.',
        manRot='Manutenção', manA='Voltamos', manB='já, já.',
        manTxt='Estamos melhorando algumas coisas. A previsão é voltar às 22:00, horário de Brasília. O que você fez está salvo.',
        tentar='Tentar de novo', irInicio='Ir para o início', voltar='Voltar', entrar='Entrar de novo',
        status='Status dos serviços', direitos='© 2026 Muriki',
    ),
    'en-US': dict(
        offRot='No connection', offA='You’re', offB='offline.',
        offTxt='We need a connection to save what you do. Whatever you already submitted is safe.',
        offNota='As soon as the connection is back, the page reloads on its own.',
        naoRot='Error 404', naoA='This page', naoB='doesn’t exist.',
        naoTxt='The link may be wrong, or the page has moved. Everything else is where you left it.',
        erroRot='Error 500', erroA='Something broke', erroB='on our side.',
        erroTxt='It wasn’t you. Try again in a moment; if it keeps happening, contact support and share the code.',
        erroCodigo='code', suporte='Contact support',
        sessaoRot='Session', sessaoA='Your session', sessaoB='has ended.',
        sessaoTxt='For your security, a session ends after a while without use or when it’s signed out on another device. Sign in again and pick up where you left off.',
        manRot='Maintenance', manA='Back', manB='in a bit.',
        manTxt='We’re improving a few things. We expect to be back at 10 PM, Brasília time. What you did is saved.',
        tentar='Try again', irInicio='Go to home', voltar='Go back', entrar='Sign in again',
        status='Service status', direitos='© 2026 Muriki',
    ),
    'es-ES': dict(
        offRot='Sin conexión', offA='Estás', offB='sin internet.',
        offTxt='Necesitamos conexión para guardar lo que haces. Lo que ya enviaste está guardado.',
        offNota='En cuanto vuelva la conexión, la página se recarga sola.',
        naoRot='Error 404', naoA='Esta página', naoB='no existe.',
        naoTxt='El enlace puede estar mal, o la página cambió de lugar. Lo demás sigue donde estaba.',
        erroRot='Error 500', erroA='Algo salió mal', erroB='de nuestro lado.',
        erroTxt='No fuiste tú. Inténtalo de nuevo en unos instantes; si sigue pasando, habla con soporte y comparte el código.',
        erroCodigo='código', suporte='Hablar con soporte',
        sessaoRot='Sesión', sessaoA='Tu sesión', sessaoB='terminó.',
        sessaoTxt='Por seguridad, la sesión termina después de un tiempo sin uso o cuando se cierra en otro dispositivo. Entra de nuevo y sigue donde lo dejaste.',
        manRot='Mantenimiento', manA='Volvemos', manB='enseguida.',
        manTxt='Estamos mejorando algunas cosas. Prevemos volver a las 22:00, hora de Brasilia. Lo que hiciste está guardado.',
        tentar='Intentar de nuevo', irInicio='Ir al inicio', voltar='Volver', entrar='Entrar de nuevo',
        status='Estado de los servicios', direitos='© 2026 Muriki',
    ),
}
