TEXTOS = {
    'pt-BR': dict(
        titulo='Converter duração em texto para minutos', nivel='nível Pleno', andamento='em andamento',
        salvo='salvo há 5 s', continuarIde='Continuar na IDE', enviar='Enviar solução',
        enunciado='Enunciado',
        enunciadoTexto='A agenda recebe durações digitadas por pessoas. Escreva a função e os testes que provam que ela funciona.',
        precisa='O que precisa acontecer',
        req1='Horas, minutos e segundos, em qualquer combinação.',
        req2='Segundos arredondam para o minuto mais próximo.',
        req3='Vazio ou sem número lança',
        req4='Nada depende do fuso da máquina.',
        explique='Explique sua solução', vaiAvaliacao='vai para a avaliação',
        pergunta='Por que o texto vazio lança erro em vez de devolver zero?',
        placeholder='Escreva com as suas palavras. Não precisa ser longo.',
        resposta='Zero é uma duração válida: uma pausa de 0 min existe. Se o vazio virar zero, quem chama não sabe que nada foi digitado.',
        nota='Entra na avaliação e no seu perfil de Testing.',
        dicaUsada='Dica 1 de 3 usada', verDica='Ver a dica', proximaDica='Próxima dica',
        codigo='Código', novoArquivo='Novo arquivo', novaPasta='Nova pasta', recolher='Recolher tudo',
        estrutura='Estrutura do projeto', renomear='Renomear', excluir='Excluir',
        nomeNovo='Nome do novo arquivo', criaCancela='↵ cria · esc cancela',
        travado='vem do exercício, só leitura', seu='criado por você',
        testes='Testes', passam='3 de 5 passam', esperado='esperado', recebido='recebido',
        rodou='rodou há 40 s', abrirTeste='Abrir o teste',
        editor='Editor', abertos='Arquivos abertos', rodar='Rodar testes',
        atalho='⌘ ↵ roda os testes', semAuto='sem autocompletar: aqui quem escreve é você',
    ),
    'en-US': dict(
        titulo='Convert a text duration into minutes', nivel='Mid-level', andamento='in progress',
        salvo='saved 5 s ago', continuarIde='Continue in your IDE', enviar='Submit solution',
        enunciado='Problem',
        enunciadoTexto='The calendar receives durations typed by people. Write the function and the tests that prove it works.',
        precisa='What needs to happen',
        req1='Hours, minutes and seconds, in any combination.',
        req2='Seconds round to the nearest minute.',
        req3='Empty or number-free input throws',
        req4='Nothing depends on the machine’s time zone.',
        explique='Explain your solution', vaiAvaliacao='goes into the evaluation',
        pergunta='Why does empty text throw instead of returning zero?',
        placeholder='Use your own words. It doesn’t need to be long.',
        resposta='Zero is a valid duration: a 0-minute break exists. If empty becomes zero, the caller can’t tell nothing was typed.',
        nota='Goes into the evaluation and your Testing profile.',
        dicaUsada='Hint 1 of 3 used', verDica='See the hint', proximaDica='Next hint',
        codigo='Code', novoArquivo='New file', novaPasta='New folder', recolher='Collapse all',
        estrutura='Project structure', renomear='Rename', excluir='Delete',
        nomeNovo='New file name', criaCancela='↵ create · esc cancel',
        travado='from the exercise, read-only', seu='created by you',
        testes='Tests', passam='3 of 5 pass', esperado='expected', recebido='received',
        rodou='ran 40 s ago', abrirTeste='Open the test',
        editor='Editor', abertos='Open files', rodar='Run tests',
        atalho='⌘ ↵ runs the tests', semAuto='no autocomplete: here, you write the code',
    ),
    'es-ES': dict(
        titulo='Convertir una duración en texto a minutos', nivel='nivel intermedio', andamento='en curso',
        salvo='guardado hace 5 s', continuarIde='Seguir en el IDE', enviar='Enviar solución',
        enunciado='Enunciado',
        enunciadoTexto='La agenda recibe duraciones escritas por personas. Escribe la función y las pruebas que demuestran que funciona.',
        precisa='Qué tiene que pasar',
        req1='Horas, minutos y segundos, en cualquier combinación.',
        req2='Los segundos se redondean al minuto más cercano.',
        req3='Vacío o sin número lanza',
        req4='Nada depende de la zona horaria de la máquina.',
        explique='Explica tu solución', vaiAvaliacao='va a la evaluación',
        pergunta='¿Por qué el texto vacío lanza un error en lugar de devolver cero?',
        placeholder='Escríbelo con tus palabras. No tiene que ser largo.',
        resposta='Cero es una duración válida: una pausa de 0 min existe. Si el vacío pasa a ser cero, quien llama no sabe que no se escribió nada.',
        nota='Entra en la evaluación y en tu perfil de Testing.',
        dicaUsada='Pista 1 de 3 usada', verDica='Ver la pista', proximaDica='Siguiente pista',
        codigo='Código', novoArquivo='Nuevo archivo', novaPasta='Nueva carpeta', recolher='Contraer todo',
        estrutura='Estructura del proyecto', renomear='Renombrar', excluir='Eliminar',
        nomeNovo='Nombre del nuevo archivo', criaCancela='↵ crea · esc cancela',
        travado='viene del ejercicio, solo lectura', seu='creado por ti',
        testes='Pruebas', passam='3 de 5 pasan', esperado='esperado', recebido='recibido',
        rodou='se ejecutó hace 40 s', abrirTeste='Abrir la prueba',
        editor='Editor', abertos='Archivos abiertos', rodar='Ejecutar pruebas',
        atalho='⌘ ↵ ejecuta las pruebas', semAuto='sin autocompletar: aquí escribes tú',
    ),
}

assert all(set(v) == set(TEXTOS['pt-BR']) for v in TEXTOS.values()), 'chaves diferentes entre idiomas'
