# Textos da trilha bloqueada e do ganho de trilha (2026-10-01), nos três idiomas da web.
# Regra: swell-docs/muriki-api/ideas/2026-10-01-desbloqueio-de-trilha.md. Os nomes das trilhas e das etapas
# vêm da API como o conteúdo escreve (pt), então ficam fora daqui.

TEXTOS = {
    'pt-BR': dict(
        liberadaSelo='liberada',
        trTitulo='Trilhas',
        trSub='Uma sequência de exercícios por competência, no seu nível. A próxima etapa muda com o que você mostra.',
        porOnde='Por onde começar', comecarTrilha='Começar a trilha', verBoasVindas='Ver as boas-vindas de novo',
        oCaminho='O caminho', verMapa='Ver o mapa', comecar='Começar', continuar='Continuar',
        jsNome='JavaScript', arqNome='Arquitetura',
        feitasDe='feitas', de='de',
        liberaEm='libera em Pleno',
        paraLiberar='Para liberar, chegue a Pleno em JavaScript',
        faltam='faltam 4 etapas', maisDuas='+2',
        abrirMesmo='Abrir mesmo assim',
        voltarTrilhas='Trilhas',
        avisoTit='Esta trilha começa em Pleno',
        avisoTxt='Você está em Junior. Dá para seguir mesmo assim: os exercícios vão pedir o que você ainda não confirmou. Para chegar a Pleno, faltam 4 etapas nas trilhas de JavaScript.',
        verCaminho='Ver o caminho na Evolução', entendi='Entendi',
        aProxima='a próxima', depois='depois', nivelPleno='Pleno', etapas3='3 etapas',
        trilhaLiberada='Trilha liberada',
        liberadaTit='Arquitetura de sistemas está liberada',
        liberadaTxt='Você confirmou Pleno em JavaScript. A trilha que desenha como as peças de um sistema web conversam começa aqui.',
        agoraNao='Agora não',
    ),
    'en-US': dict(
        liberadaSelo='unlocked',
        trTitulo='Tracks',
        trSub='A sequence of exercises per competency, at your level. The next step changes with what you show.',
        porOnde='Where to start', comecarTrilha='Start the track', verBoasVindas='See the welcome again',
        oCaminho='The path', verMapa='See the map', comecar='Start', continuar='Continue',
        jsNome='JavaScript', arqNome='Architecture',
        feitasDe='done', de='of',
        liberaEm='unlocks at Mid-level',
        paraLiberar='To unlock it, reach Mid-level in JavaScript',
        faltam='4 steps to go', maisDuas='+2',
        abrirMesmo='Open it anyway',
        voltarTrilhas='Tracks',
        avisoTit='This track starts at Mid-level',
        avisoTxt='You are at Junior. You can still go ahead: the exercises will ask for what you have not confirmed yet. To reach Mid-level, there are 4 steps left in the JavaScript tracks.',
        verCaminho='See the path in Progress', entendi='Got it',
        aProxima='up next', depois='later', nivelPleno='Mid-level', etapas3='3 steps',
        trilhaLiberada='Track unlocked',
        liberadaTit='System architecture is unlocked',
        liberadaTxt='You confirmed Mid-level in JavaScript. The track about how the pieces of a web system talk to each other starts here.',
        agoraNao='Not now',
    ),
    'es-ES': dict(
        liberadaSelo='liberada',
        trTitulo='Rutas',
        trSub='Una secuencia de ejercicios por competencia, en tu nivel. La próxima etapa cambia con lo que muestras.',
        porOnde='Por dónde empezar', comecarTrilha='Empezar la ruta', verBoasVindas='Ver la bienvenida otra vez',
        oCaminho='El camino', verMapa='Ver el mapa', comecar='Empezar', continuar='Continuar',
        jsNome='JavaScript', arqNome='Arquitectura',
        feitasDe='hechas', de='de',
        liberaEm='se libera en nivel intermedio',
        paraLiberar='Para liberarla, llega a nivel intermedio en JavaScript',
        faltam='faltan 4 etapas', maisDuas='+2',
        abrirMesmo='Abrir de todos modos',
        voltarTrilhas='Rutas',
        avisoTit='Esta ruta empieza en nivel intermedio',
        avisoTxt='Estás en Junior. Puedes seguir de todos modos: los ejercicios van a pedir lo que aún no confirmaste. Para llegar a nivel intermedio, faltan 4 etapas en las rutas de JavaScript.',
        verCaminho='Ver el camino en Evolución', entendi='Entendido',
        aProxima='la siguiente', depois='después', nivelPleno='nivel intermedio', etapas3='3 etapas',
        trilhaLiberada='Ruta liberada',
        liberadaTit='Arquitectura de sistemas está liberada',
        liberadaTxt='Confirmaste nivel intermedio en JavaScript. La ruta que diseña cómo conversan las piezas de un sistema web empieza aquí.',
        agoraNao='Ahora no',
    ),
}
