# Textos da tela do exercício de arquitetura (a bancada), nos três idiomas da web.
# Plano: swell-docs/muriki-code-platform/features/exercicio-arquitetura.

TEXTOS = {
    'pt-BR': dict(
        simular='Simular', sairSim='Sair da simulação', levantarApi='Levantar API de links', levantarTudo='Levantar tudo',
        simResumo='<b>1 peça fora do ar</b> · Redis e Postgres ficaram sem caminho a partir de Navegador.',
        provedor='Provedor', generico='Genérico', aws='AWS', gcp='GCP', azure='Azure',
        provedorDica='Cada peça ganha o primeiro serviço do tipo. Troque na peça selecionada.',
        provedorDicaGenerico='As peças ficam genéricas. Escolha um provedor para ver os serviços.',
        grupos='Grupos', gruposDica='Arraste peças e grupos para dentro. Com um grupo selecionado, o clique põe dentro dele.',
        gRegiao='Região', gZona='Zona', gVpc='VPC', gPublica='Sub-rede pública', gPrivada='Sub-rede privada',
        servico='Serviço', ligarA='Ligar a…', moverPara='Mover para…', pBalanceador='Balanceador',
        nProducao='produção', nEntrada='Entrada', statusNuvem='5 peças · 4 ligações · 4 grupos',
        aproximadoDica='Aproximado: o serviço faz o papel, mas não é o equivalente exato do tipo.',
        trilhaArq='Arquitetura', titulo='Encurtador de links', chipSD='System Design', nivel='nível Pleno',
        andamento='em andamento', salvo='salvo há 5 s', continuarIde='Continuar na IDE', enviar='Enviar solução',
        enunciado='Enunciado',
        enunciadoTexto='Desenhe um encurtador de links como o bit.ly: a pessoa manda uma URL longa e recebe um código curto. Quem abre o código é levado à URL original.',
        precisa='O que precisa acontecer',
        req1='10 mil redirecionamentos por segundo, 100 links novos por segundo.',
        req2='Redirecionar responde em menos de 50 ms.',
        req3='Cada acesso é contado, sem atrasar o redirecionamento.',
        explique='Explique sua solução', vaiAvaliacao='vai para a avaliação',
        pergunta='Por que o seu desenho aguenta os redirecionamentos?',
        placeholder='Escreva com as suas palavras. Não precisa ser longo.',
        nota='Entra na avaliação e no seu perfil de System Design.',
        dicas='Dicas', dicasDisp='3 dicas disponíveis', pedirDica='Pedir dica',
        pecas='Peças', regras='Regras', passam='2 de 3 passam',
        pCliente='Cliente', pApi='API', pBanco='Banco', pCache='Cache', pFila='Fila', pWorker='Worker', pCdn='CDN',
        r1='O cliente só fala com a API', r2='Redirecionar não lê o banco toda vez',
        r3='Os acessos são contados sem atrasar o redirecionamento',
        dicaVerificar='Verifique com ⌘ ↵ para ver as regras',
        chama='chama', le='lê', escreve='escreve', publica='publica', consome='consome',
        renomear='Renomear', apagar='Apagar', verificar='Verificar',
        nNavegador='Navegador', nApi='API de links', nRedis='Redis', nPostgres='Postgres', rotuloCache='código → URL',
        status='4 peças · 3 ligações', atalho='⌘ ↵ verifica', bancada='Bancada do diagrama',
    ),
    'en-US': dict(
        simular='Simulate', sairSim='Leave simulation', levantarApi='Restore Links API', levantarTudo='Restore all',
        simResumo='<b>1 piece down</b> · Redis and Postgres have no path from Browser.',
        provedor='Provider', generico='Generic', aws='AWS', gcp='GCP', azure='Azure',
        provedorDica='Each piece gets the first service of its type. Change it on the selected piece.',
        provedorDicaGenerico='Pieces stay generic. Pick a provider to see the services.',
        grupos='Groups', gruposDica='Drag pieces and groups inside. With a group selected, a click puts it inside.',
        gRegiao='Region', gZona='Zone', gVpc='VPC', gPublica='Public subnet', gPrivada='Private subnet',
        servico='Service', ligarA='Connect to…', moverPara='Move to…', pBalanceador='Load balancer',
        nProducao='production', nEntrada='Entry', statusNuvem='5 pieces · 4 connections · 4 groups',
        aproximadoDica='Approximate: the service plays the role, but it is not an exact match for the type.',
        trilhaArq='Architecture', titulo='Link shortener', chipSD='System Design', nivel='Mid-level',
        andamento='in progress', salvo='saved 5 s ago', continuarIde='Continue in your IDE', enviar='Submit solution',
        enunciado='Problem',
        enunciadoTexto='Design a link shortener like bit.ly: a person sends a long URL and gets a short code back. Whoever opens the code lands on the original URL.',
        precisa='What needs to happen',
        req1='10k redirects per second, 100 new links per second.',
        req2='A redirect answers in under 50 ms.',
        req3='Every visit is counted without slowing the redirect.',
        explique='Explain your solution', vaiAvaliacao='goes into the evaluation',
        pergunta='Why does your design handle the redirects?',
        placeholder='Use your own words. It doesn’t need to be long.',
        nota='Goes into the evaluation and your System Design profile.',
        dicas='Hints', dicasDisp='3 hints available', pedirDica='Ask for a hint',
        pecas='Pieces', regras='Rules', passam='2 of 3 pass',
        pCliente='Client', pApi='API', pBanco='Database', pCache='Cache', pFila='Queue', pWorker='Worker', pCdn='CDN',
        r1='The client only talks to the API', r2='A redirect doesn’t read the database every time',
        r3='Visits are counted without slowing the redirect',
        dicaVerificar='Check with ⌘ ↵ to see the rules',
        chama='calls', le='reads', escreve='writes', publica='publishes', consome='consumes',
        renomear='Rename', apagar='Delete', verificar='Check',
        nNavegador='Browser', nApi='Links API', nRedis='Redis', nPostgres='Postgres', rotuloCache='code → URL',
        status='4 pieces · 3 connections', atalho='⌘ ↵ checks', bancada='Diagram workbench',
    ),
    'es-ES': dict(
        simular='Simular', sairSim='Salir de la simulación', levantarApi='Levantar API de enlaces', levantarTudo='Levantar todo',
        simResumo='<b>1 pieza caída</b> · Redis y Postgres quedaron sin camino desde Navegador.',
        provedor='Proveedor', generico='Genérico', aws='AWS', gcp='GCP', azure='Azure',
        provedorDica='Cada pieza recibe el primer servicio del tipo. Cámbialo en la pieza seleccionada.',
        provedorDicaGenerico='Las piezas quedan genéricas. Elige un proveedor para ver los servicios.',
        grupos='Grupos', gruposDica='Arrastra piezas y grupos adentro. Con un grupo seleccionado, el clic lo pone dentro.',
        gRegiao='Región', gZona='Zona', gVpc='VPC', gPublica='Subred pública', gPrivada='Subred privada',
        servico='Servicio', ligarA='Conectar con…', moverPara='Mover a…', pBalanceador='Balanceador',
        nProducao='producción', nEntrada='Entrada', statusNuvem='5 piezas · 4 conexiones · 4 grupos',
        aproximadoDica='Aproximado: el servicio cumple el papel, pero no es el equivalente exacto del tipo.',
        trilhaArq='Arquitectura', titulo='Acortador de enlaces', chipSD='System Design', nivel='nivel intermedio',
        andamento='en curso', salvo='guardado hace 5 s', continuarIde='Seguir en el IDE', enviar='Enviar solución',
        enunciado='Enunciado',
        enunciadoTexto='Diseña un acortador de enlaces como bit.ly: la persona envía una URL larga y recibe un código corto. Quien abre el código llega a la URL original.',
        precisa='Lo que tiene que pasar',
        req1='10 mil redirecciones por segundo, 100 enlaces nuevos por segundo.',
        req2='Una redirección responde en menos de 50 ms.',
        req3='Cada visita se cuenta sin retrasar la redirección.',
        explique='Explica tu solución', vaiAvaliacao='va a la evaluación',
        pergunta='¿Por qué tu diseño aguanta las redirecciones?',
        placeholder='Escríbelo con tus palabras. No hace falta que sea largo.',
        nota='Entra en la evaluación y en tu perfil de System Design.',
        dicas='Pistas', dicasDisp='3 pistas disponibles', pedirDica='Pedir pista',
        pecas='Piezas', regras='Reglas', passam='2 de 3 pasan',
        pCliente='Cliente', pApi='API', pBanco='Base de datos', pCache='Caché', pFila='Cola', pWorker='Worker', pCdn='CDN',
        r1='El cliente solo habla con la API', r2='Redirigir no lee la base de datos cada vez',
        r3='Las visitas se cuentan sin retrasar la redirección',
        dicaVerificar='Verifica con ⌘ ↵ para ver las reglas',
        chama='llama', le='lee', escreve='escribe', publica='publica', consome='consume',
        renomear='Renombrar', apagar='Borrar', verificar='Verificar',
        nNavegador='Navegador', nApi='API de enlaces', nRedis='Redis', nPostgres='Postgres', rotuloCache='código → URL',
        status='4 piezas · 3 conexiones', atalho='⌘ ↵ verifica', bancada='Banco del diagrama',
    ),
}
