# Textos da Evolução refeita em 2026-10-01 (competências e trilhas reais do conteúdo), nos três idiomas.
# Os nomes das competências e das trilhas vêm da API como o conteúdo escreve (pt), então ficam fora daqui.

TEXTOS = {
    'pt-BR': dict(
        evTitulo='Evolução',
        evSub='Sempre contra o seu próprio histórico. O nível só sobe, e nada aqui compara você com outra pessoa.',
        comoMedido='Como o nível é medido',
        competencias='Suas competências', grupoJs='JavaScript', grupoArq='Arquitetura',
        colComp='Competência', colNivel='Nível', colOrigem='De onde vem', colCaminho='Caminho na trilha',
        origemConfirmado='confirmado nos exercícios', origemContou='você contou', origemTempo='pelo seu tempo de código',
        etapasDe='Etapas de', de='de', semEtapas='sem etapas ainda',
        nasTrilhas='Nas trilhas', feitas='feitas', cobertas='cobertas pelo seu nível', pendentes='pendentes',
        abrirTrilha='Abrir a trilha',
        noTempo='Evolução no tempo', noTempoSub='O nível de cada competência, semana a semana. O ponto marca quando um exercício confirmou.',
        legConfirmado='confirmado', legDeclarado='declarado',
        jul='jul', ago='ago', set='set',
        trajetoria='Trajetória', trajetoriaSub='A mesma competência, uma solução antiga ao lado de uma recente.',
        antes='julho · contador de cliques', agora='setembro · memoize',
        medida='Funções que mexem em estado de fora', medidaAntes='3', medidaAgora='0',
        verTodas='Ver todas',
        nivelFund='Fundamentos', nivelJunior='Junior', nivelPleno='Pleno', nivelSenior='Senior',
    ),
    'en-US': dict(
        evTitulo='Progress',
        evSub='Always against your own history. Your level only goes up, and nothing here compares you with anyone else.',
        comoMedido='How the level is measured',
        competencias='Your competencies', grupoJs='JavaScript', grupoArq='Architecture',
        colComp='Competency', colNivel='Level', colOrigem='Where it comes from', colCaminho='Path in the tracks',
        origemConfirmado='confirmed by exercises', origemContou='you told us', origemTempo='from your coding time',
        etapasDe='Steps at', de='of', semEtapas='no steps yet',
        nasTrilhas='In the tracks', feitas='done', cobertas='covered by your level', pendentes='to do',
        abrirTrilha='Open the track',
        noTempo='Over time', noTempoSub='Each competency’s level, week by week. A dot marks when an exercise confirmed it.',
        legConfirmado='confirmed', legDeclarado='declared',
        jul='Jul', ago='Aug', set='Sep',
        trajetoria='Trajectory', trajetoriaSub='The same competency, an old solution next to a recent one.',
        antes='July · click counter', agora='September · memoize',
        medida='Functions that change outside state', medidaAntes='3', medidaAgora='0',
        verTodas='See all',
        nivelFund='Foundations', nivelJunior='Junior', nivelPleno='Mid-level', nivelSenior='Senior',
    ),
    'es-ES': dict(
        evTitulo='Evolución',
        evSub='Siempre frente a tu propio historial. El nivel solo sube, y nada aquí te compara con otra persona.',
        comoMedido='Cómo se mide el nivel',
        competencias='Tus competencias', grupoJs='JavaScript', grupoArq='Arquitectura',
        colComp='Competencia', colNivel='Nivel', colOrigem='De dónde viene', colCaminho='Camino en la ruta',
        origemConfirmado='confirmado en los ejercicios', origemContou='lo dijiste tú', origemTempo='por tu tiempo programando',
        etapasDe='Etapas de', de='de', semEtapas='sin etapas aún',
        nasTrilhas='En las rutas', feitas='hechas', cobertas='cubiertas por tu nivel', pendentes='pendientes',
        abrirTrilha='Abrir la ruta',
        noTempo='En el tiempo', noTempoSub='El nivel de cada competencia, semana a semana. El punto marca cuando un ejercicio lo confirmó.',
        legConfirmado='confirmado', legDeclarado='declarado',
        jul='jul', ago='ago', set='sept',
        trajetoria='Trayectoria', trajetoriaSub='La misma competencia, una solución antigua junto a una reciente.',
        antes='julio · contador de clics', agora='septiembre · memoize',
        medida='Funciones que cambian estado de fuera', medidaAntes='3', medidaAgora='0',
        verTodas='Ver todas',
        nivelFund='Fundamentos', nivelJunior='Junior', nivelPleno='nivel intermedio', nivelSenior='Senior',
    ),
}
