# Textos do Início no primeiro dia: a pessoa terminou o onboarding (e talvez o perfil de
# aprendizado) e ainda não fez nenhum exercício. Somam-se ao COMUM.

INICIO = {
    'pt-BR': dict(
        titulo='Boas-vindas, Rafael.',
        sub='O seu Code está pronto. Comece pelo primeiro exercício: ele já conta para o seu perfil.',
        proximo='Próximo passo', entra='entra em Testing e Debugging',
        exTitulo='Converter duração em texto para minutos',
        exTxt='Tem testes, dicas sob pedido e, no fim, uma pergunta para você explicar a sua solução. Uns 20 minutos.',
        comecar='Começar o primeiro exercício', trilha='Escolher uma trilha', emBreve='em breve',
        contou='O que você nos contou', ajustar='Ajustar',
        nivel='Experiência', linguas='Linguagens', objetivos='Objetivos',
        pulouTxt='Você pulou esse passo no primeiro acesso. Contar agora ajuda o Code a escolher trilhas e o Peer a falar no seu nível.',
        contarAgora='Contar agora', oAprender='Aprender', oEntregar='Entregar mais rápido',
        mapa='O que tem no Code',
        mExercicios='Exercícios', mExerciciosTxt='Problemas com testes, no navegador. O primeiro já está separado.',
        mTrilhas='Trilhas', mTrilhasTxt='Sequências de exercícios por competência, no seu nível.',
        mAvaliacoes='Avaliações', mAvaliacoesTxt='Aparecem depois do primeiro envio, com o porquê de cada nota.',
        mPeer='Peer na IDE', mPeerTxt='Pergunta em vez de responder, direto no VS Code ou no Cursor.', conectar='Conectar',
        mPlayground='Playground', mPlaygroundTxt='Código livre, sem enunciado nem nota, com o Peer do lado.', abrir='Abrir',
        depoisPrimeiro='depois do 1º envio',
        perfil='Seu perfil de competência',
        perfilTxt='Começa em Pleno em tudo, pela experiência que você escolheu. Cada exercício enviado confirma ou ajusta uma competência.',
        verPerfil='Ver o perfil',
        planoRot='Plano', planoTxt='Pro em teste grátis até 1º de outubro. Depois, você escolhe entre ficar no Pro ou voltar ao Starter.',
        diasRestantes='6 dias restantes', verPlanos='Ver planos',
    ),
    'en-US': dict(
        titulo='Welcome, Rafael.',
        sub='Your Code is ready. Start with the first exercise: it already counts toward your profile.',
        proximo='Next step', entra='counts toward Testing and Debugging',
        exTitulo='Convert a text duration into minutes',
        exTxt='It has tests, hints on request and, at the end, a question for you to explain your solution. About 20 minutes.',
        comecar='Start the first exercise', trilha='Pick a track', emBreve='soon',
        contou='What you told us', ajustar='Adjust',
        nivel='Experience', linguas='Languages', objetivos='Goals',
        pulouTxt='You skipped this step on your first access. Telling us now helps Code pick tracks and the Peer talk at your level.',
        contarAgora='Tell us now', oAprender='Learn', oEntregar='Ship faster',
        mapa='What’s in Code',
        mExercicios='Exercises', mExerciciosTxt='Problems with tests, in the browser. The first one is already picked.',
        mTrilhas='Tracks', mTrilhasTxt='Sequences of exercises per competency, at your level.',
        mAvaliacoes='Evaluations', mAvaliacoesTxt='They show up after your first submission, with the why behind each grade.',
        mPeer='Peer in your IDE', mPeerTxt='Asks instead of answering, right in VS Code or Cursor.', conectar='Connect',
        mPlayground='Playground', mPlaygroundTxt='Free code, no brief and no grade, with the Peer beside you.', abrir='Open',
        depoisPrimeiro='after 1st submission',
        perfil='Your competency profile',
        perfilTxt='It starts at Mid-level in everything, from the experience you chose. Each exercise you submit confirms or adjusts a competency.',
        verPerfil='See the profile',
        planoRot='Plan', planoTxt='Pro on a free trial until October 1. After that, you choose between staying on Pro or going back to Starter.',
        diasRestantes='6 days left', verPlanos='See plans',
    ),
    'es-ES': dict(
        titulo='Te damos la bienvenida, Rafael.',
        sub='Tu Code está listo. Empieza por el primer ejercicio: ya cuenta para tu perfil.',
        proximo='Siguiente paso', entra='cuenta para Testing y Debugging',
        exTitulo='Convertir una duración en texto a minutos',
        exTxt='Tiene pruebas, pistas a pedido y, al final, una pregunta para que expliques tu solución. Unos 20 minutos.',
        comecar='Empezar el primer ejercicio', trilha='Elegir una ruta', emBreve='pronto',
        contou='Lo que nos contaste', ajustar='Ajustar',
        nivel='Experiencia', linguas='Lenguajes', objetivos='Objetivos',
        pulouTxt='Saltaste este paso en el primer acceso. Contarlo ahora ayuda a Code a elegir rutas y al Peer a hablar a tu nivel.',
        contarAgora='Contar ahora', oAprender='Aprender', oEntregar='Entregar más rápido',
        mapa='Qué hay en Code',
        mExercicios='Ejercicios', mExerciciosTxt='Problemas con pruebas, en el navegador. El primero ya está elegido.',
        mTrilhas='Rutas', mTrilhasTxt='Secuencias de ejercicios por competencia, a tu nivel.',
        mAvaliacoes='Evaluaciones', mAvaliacoesTxt='Aparecen después del primer envío, con el porqué de cada nota.',
        mPeer='Peer en el IDE', mPeerTxt='Pregunta en lugar de responder, directo en VS Code o Cursor.', conectar='Conectar',
        mPlayground='Playground', mPlaygroundTxt='Código libre, sin enunciado ni nota, con el Peer al lado.', abrir='Abrir',
        depoisPrimeiro='tras el 1.er envío',
        perfil='Tu perfil de competencias',
        perfilTxt='Empieza en Intermedio en todo, por la experiencia que elegiste. Cada ejercicio enviado confirma o ajusta una competencia.',
        verPerfil='Ver el perfil',
        planoRot='Plan', planoTxt='Pro en prueba gratis hasta el 1 de octubre. Después, eliges entre seguir en Pro o volver a Starter.',
        diasRestantes='6 días restantes', verPlanos='Ver planes',
    ),
}
