# Textos das páginas de sistema: sem internet, página não encontrada, erro inesperado, sessão
# expirada e manutenção. Somam-se ao COMUM. Nenhuma culpa a pessoa, e toda tela diz o que fazer.

SISTEMA = {
    'pt-BR': dict(
        offTit='Você está sem internet',
        offTxt='O Code precisa de conexão para rodar os testes e salvar o seu progresso. O que você já enviou está salvo.',
        offNota='Assim que a conexão voltar, a página recarrega sozinha.',
        tentar='Tentar de novo',
        naoTit='Esta página não existe',
        naoTxt='O link pode estar errado, ou a página mudou de lugar.',
        irInicio='Ir para o início', voltar='Voltar',
        erroTit='Algo deu errado do nosso lado',
        erroTxt='Não foi você. Tente de novo em alguns instantes; se continuar, fale com o suporte e passe o código abaixo.',
        erroCodigo='Código do erro', suporte='Falar com o suporte',
        sessaoTit='Sua sessão terminou',
        sessaoTxt='Por segurança, a sessão termina depois de um tempo sem uso ou quando é encerrada em outro aparelho. Entre de novo para continuar de onde parou.',
        entrar='Entrar de novo',
        manTit='O Code está em manutenção',
        manTxt='Estamos melhorando algumas coisas. A previsão é voltar às 22:00, horário de Brasília. O seu progresso está salvo.',
    ),
    'en-US': dict(
        offTit='You’re offline',
        offTxt='Code needs a connection to run the tests and save your progress. What you already submitted is saved.',
        offNota='As soon as the connection is back, the page reloads on its own.',
        tentar='Try again',
        naoTit='This page doesn’t exist',
        naoTxt='The link may be wrong, or the page has moved.',
        irInicio='Go to home', voltar='Go back',
        erroTit='Something went wrong on our side',
        erroTxt='It wasn’t you. Try again in a moment; if it keeps happening, contact support and share the code below.',
        erroCodigo='Error code', suporte='Contact support',
        sessaoTit='Your session ended',
        sessaoTxt='For your security, a session ends after a while without use or when it’s signed out on another device. Sign in again to pick up where you left off.',
        entrar='Sign in again',
        manTit='Code is under maintenance',
        manTxt='We’re improving a few things. We expect to be back at 10 PM, Brasília time. Your progress is saved.',
    ),
    'es-ES': dict(
        offTit='Estás sin internet',
        offTxt='Code necesita conexión para ejecutar las pruebas y guardar tu progreso. Lo que ya enviaste está guardado.',
        offNota='En cuanto vuelva la conexión, la página se recarga sola.',
        tentar='Intentar de nuevo',
        naoTit='Esta página no existe',
        naoTxt='El enlace puede estar mal, o la página cambió de lugar.',
        irInicio='Ir al inicio', voltar='Volver',
        erroTit='Algo salió mal de nuestro lado',
        erroTxt='No fuiste tú. Inténtalo de nuevo en unos instantes; si sigue pasando, habla con soporte y comparte el código de abajo.',
        erroCodigo='Código del error', suporte='Hablar con soporte',
        sessaoTit='Tu sesión terminó',
        sessaoTxt='Por seguridad, la sesión termina después de un tiempo sin uso o cuando se cierra en otro dispositivo. Entra de nuevo para seguir donde lo dejaste.',
        entrar='Entrar de nuevo',
        manTit='Code está en mantenimiento',
        manTxt='Estamos mejorando algunas cosas. Prevemos volver a las 22:00, hora de Brasilia. Tu progreso está guardado.',
    ),
}
